recipeyak/recipeyak

- README.md
- backend/Dockerfile-prod
- backend/backend/settings.py
- backend/bootstrap-prod.sh
- docker-compose-prod.yml
- frontend/bootstrap.sh
We need to copy over the static files at runtime.
> Fix volumes for django and react bundle

- frontend/config/webpack.config.prod.js
This may need to be restricted for production usage
> Enable creation of source maps

- frontend/src/components/UserHome.jsx
this resulted in the login page not redirecting correctly
> fix user stats

- frontend/src/components/scss/main.scss
> Added: some overrides for printing of the recipe

- backend/Dockerfile-dev
- backend/Dockerfile-prod
- backend/Pipfile
- backend/Pipfile.lock
- backend/backend/settings.py
- backend/core/models.py
- backend/core/views.py
- backend/rest_auth/registration/views.py
- backend/rest_auth/views.py
- frontend/config/webpack.config.prod.js
- nginx/nginx.conf
- Fix CSP issue with Sentry
- Fix Pipenv issue with package install failing
- Add JSON logging to Django
> Add logging for CloudWatch collection

- frontend/config/webpack.config.dev.js
- frontend/config/webpack.config.prod.js
- frontend/src/components/App.jsx
- frontend/src/components/scss/main.scss
Now we can set variables and use bulma properly
> Updated: webpack and imports so we use bulma sass

- frontend/src/store/reducers/rootReducer.test.js
- frontend/src/store/store.js
Now we don't lose location history
> Updated: clearing of reducers on logout

- .gitignore
- frontend/.eslintrc.js
- frontend/src/components/App.jsx
- frontend/src/components/AuthContainer.jsx
- frontend/src/components/Login.jsx
- frontend/src/components/Logo.jsx
- frontend/src/components/PasswordReset.jsx
- frontend/src/components/Signup.jsx
- frontend/src/components/scss/helpers.scss
Now they use more of the $primary-color
> Updated: Login, Signup, and Password Reset

- frontend/src/components/AuthContainer.jsx
- frontend/src/components/Login.jsx
- frontend/src/components/PasswordReset.jsx
- frontend/src/components/Signup.jsx
- frontend/src/components/scss/main.scss
Increased font-weight of recipe yak text on login page
> Updated: tabs to not have text decoration

- frontend/config/webpack.config.dev.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/App.jsx
- frontend/src/index.js
- frontend/tsconfig.json
Fixes issue with async lambda functions
see: https://github.com/gaearon/react-hot-loader
> Updgrade: react hot loader to version 4.0

- frontend/config/webpack.config.dev.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/App.jsx
- frontend/src/components/Login.jsx
- frontend/src/components/RecipeList.jsx
- frontend/src/index.js
- frontend/tsconfig.json
This reverts commit 37e87e8a4a0dbeede4c76348d3c4c9c85bc1810b.
> Revert "Updgrade: react hot loader to version 4.0"

- backend/Pipfile.lock
This is probably some virus I'm allowing. It's really sketchy that the
SHA changed and the version didn't...
> Fix cffi version

- frontend/src/components/OAuth.jsx
- frontend/src/components/SocialButtons.jsx
This was literally a typo
I also added a default argument to OAuth.jsx
> Fix OAuth error not displaying on Login/Signup pages

- docker-compose-dev.yml
We need to figure out the caveats with this
> Add caching for docker osxfs

- backend/bootstrap-dev.sh
- backend/bootstrap-prod.sh
- backend/wait-for-it.sh
- upload
> Replace netcat with wait-for-it.sh. Improve image uploading w/ xargs

- backend/core/test_shopping_list.py
- backend/core/utils.py
issue where order of plural and singular would affect merging
simplified combining_ingredients function
> Fix: combining plural and singular

- backend/backend/middleware.py
- backend/backend/settings.py
- backend/core/test_middleware.py
https://w3c.github.io/server-timing/#the-server-timing-header-field
> Add: server timing middleware

- backend/core/models.py
- backend/core/test_models.py
It's a bad idea to change the way people expect Django to behave.
> Remove soft delete

- backend/core/migrations/0048_auto_20180510_2050.py
The original migration was kind of borked. This is the simplest solution that works.
> Fix step position migration

- frontend/src/components/Schedule.jsx
- frontend/src/components/ShoppingList.jsx
- frontend/src/components/scss/main.scss
hide some buttons, inputs, etc.
> Fix printing of shopping list

- frontend/src/components/App.jsx
- frontend/src/components/Calendar.jsx
- frontend/src/components/CalendarDayItem.jsx
- frontend/src/components/HelpMenuModal.jsx
- frontend/src/components/scss/main.scss
Also add help modal triggered via `?`
> Add keybind for deleting scheduled recipe

- frontend/src/components/DatePickerForm.jsx
- frontend/src/components/scss/helpers.scss
> Update: min-width of date picker

- backend/Pipfile.lock
- backend/core/test_shopping_list.py
- backend/core/utils.py
- backend/core/views.py
> Add origin field to shoppinglist ingredients

- frontend/src/urls.test.js
- frontend/src/urls.ts
Use the built-in encodeURIComponent
> Fix hash in urls from recipe names

- backend/core/conftest.py
- backend/core/search.py
- backend/core/serializers.py
- backend/core/test_recipes.py
- backend/core/test_search.py
- backend/core/views.py
- backend/tox.ini
A query parameter can be used to search recipes
e.g. /recipes?q=some%20query
> Add search option to recipes endpoint

- frontend/src/components/Dropdown.jsx
- frontend/src/components/Nav.jsx
- frontend/src/components/NotificationsDropdown.jsx
add option so dropdown isn't p-rel and it defaults to the parent
> Fix nav dropdowns

- .circleci/config.yml
build gets combined with lint for frontend
> refactor circle jobs

- backend/core/recipes/search.py
- backend/core/recipes/test_search.py
This should resolve the issue of duplicate results, but a test should be
added to make sure
> Fix uniqueness issue with search

- frontend/src/components/Calendar.tsx
- frontend/src/components/CalendarDay.tsx
- frontend/src/store/reducers/calendar.ts
- Remove a filter that was hiding messages that had not been saved yet.
- Improve drop handler performance by using Promise.resolve.then to make
api calls run async.
> Display unsaved scheduled messages. Improve drop handler performance.

- frontend/package.json
- frontend/src/settings.ts
- frontend/src/store/store.ts
- frontend/yarn.lock
Logging to console can be helpful for seeing where actions occur in comparison
to other console events.
> Add redux-logger

- frontend/config/jest/localStorage.js
- frontend/package.json
- frontend/src/components/ErrorBoundary.test.tsx
- frontend/src/components/Owner.tsx
- frontend/src/components/StepContainer.tsx
- frontend/src/components/TeamInvite.tsx
- frontend/src/index.tsx
- frontend/src/store/actions.ts
- frontend/src/store/localStorage.ts
- frontend/src/store/store.ts
- frontend/tslint.json
- frontend/yarn.lock
Returning errors instead of throw forces us to handle error cases.
https://github.com/jonaskello/tslint-immutable#no-throw
- add localStorage mock
- cull a lot of unnecessary throws
- report all axios errors
> Add no-throw lint

- frontend/src/index.tsx
I think this helps with debugging a bit
> Log app version and sentry DSN

- frontend/src/components/RecipeItem.tsx
- frontend/src/components/scss/helpers.scss
Also divide recipe item into smaller components
> Refactor recipe item with schedule in lower right

- frontend/src/components/Calendar.tsx
- frontend/src/components/Schedule.tsx
- frontend/src/date.test.ts
- frontend/src/date.ts
refactor calendar into smaller components
> have calendar only display three weeks at a time

- frontend/src/components/Schedule.tsx
- frontend/src/components/Tabs.tsx
- frontend/src/components/Team.tsx
- frontend/src/components/scss/main.scss
> update tab size on schedule & refactor into tab component

- backend/core/recipes/views.py
This is kind of a hack to just over-fetch. In the future we can use a
tagged union.
> fix mismatch recipe fetch type

- frontend/src/components/DatePickerForm.tsx
- frontend/src/components/DateRangePicker/DateRangePicker.tsx
- frontend/src/components/RecipeItem.tsx
- frontend/src/components/RecipeTitle.tsx
- frontend/src/components/ShoppingList.tsx
We are now able to close using buttons. This bug was introduced with the
GlobalEvent component.
> Fix DateRangePicker and DatePicker dropdowns

- frontend/src/components/ShoppingList.tsx
> Fix date range picker behavior in shopping list

- frontend/src/api.ts
- frontend/src/components/Calendar.tsx
- frontend/src/date.ts
- frontend/src/store/actions.ts
pyFormat wasn't very descriptive
> Rename function for formating dates toDateString

- frontend/src/components/Calendar.tsx
- frontend/src/components/CalendarDay.tsx
- frontend/src/components/Owner.tsx
- frontend/src/components/Recipe.tsx
- frontend/src/components/ShoppingList.tsx
- frontend/src/components/UserHome.tsx
- frontend/src/containers/AddRecipe.ts
- frontend/src/containers/Nav.ts
- frontend/src/containers/UserHome.ts
- frontend/src/store/actions.ts
- frontend/src/store/reducers/calendar.ts
- frontend/src/store/reducers/recipes.test.ts
- frontend/src/store/reducers/recipes.ts
- frontend/src/store/reducers/shoppinglist.test.ts
- frontend/src/store/reducers/shoppinglist.ts
- frontend/src/store/reducers/teams.test.ts
- frontend/src/store/reducers/teams.ts
- frontend/src/store/reducers/user.ts
- frontend/src/store/remotedata.ts
Also add helper functions for working with WebData
> refactor reducers to use WebData and async actions

- frontend/src/components/Recipes.tsx
- frontend/src/containers/Team.ts
- frontend/src/containers/UserHome.ts
This is a little bit cheating, but it should work generally.
> Only display loaders when there isn't any data

- frontend/src/components/Recipe.tsx
- frontend/src/components/Recipes.tsx
- frontend/src/components/UserHome.tsx
- frontend/src/containers/UserHome.ts
- frontend/src/store/actions.ts
- frontend/src/store/reducers/recipes.ts
This adds WebData<> for recentRecipes, and reverts the changes that hid
loading states for browse and schedule
> fix previous update where we attempted to eliminate loading state

- backend/core/export/test_export.py
- backend/core/export/views.py
- backend/core/models.py
- backend/core/recipes/test_recipes.py
- backend/core/recipes/views.py
- backend/core/schedule/views.py
- backend/core/stats/views.py
- backend/core/teams/views.py
- backend/tox.ini
also enable strict null checking for python
> add more typehints to backend

- frontend/src/store/actions.ts
- frontend/src/urls.test.ts
- frontend/src/urls.ts
Also update slug function to be more robust
> update redirect after recipe creation

- frontend/src/components/App.tsx
- frontend/src/components/RecipeList.tsx
- frontend/src/utils/types.ts
- update PrivateRoute and PublicRoute to handle render props
- add ArgumentType to extract arg types
> Add auto focus to browse page search input

- frontend/src/components/Ingredient.tsx
- frontend/src/components/ListItem.tsx
- frontend/src/components/MetaData.tsx
- frontend/src/components/Owner.tsx
- frontend/src/components/RecipeTitle.tsx
- add cursor-pointer to recipe metadata
- make "via" regular text
> Add titles where users can click to edit in a recipe

- frontend/src/components/Settings.tsx
- frontend/src/store/reducers/user.ts
Need to move to redux and WebData<T>
> Refactor settings page into sub components

- frontend/src/components/RecipeItem.tsx
- frontend/src/components/Results.tsx
- frontend/src/components/Schedule.tsx
- frontend/src/components/scss/main.scss
> Update styling of recipe picker on schedule page

- frontend/src/store/thunks.ts
Before a recipe on the current day couldn't be moved, only copied
> allow moving of current day's scheduled recipes

- frontend/package.json
- frontend/src/http.ts
- frontend/tslint.json
- frontend/yarn.lock
Enable the new `no-promise-catch` rule
> Upgrade tslint-cake

- backend/core/schedule/test_shopping_list.py
- backend/core/schedule/utils.py
> Fix bad combine with casing

- frontend/src/components/CalendarDayItem.tsx
- frontend/src/components/DatePickerForm.tsx
- frontend/src/components/Nav.tsx
- frontend/src/components/NotificationsDropdown.tsx
- frontend/src/components/Owner.tsx
- frontend/src/components/ShoppingList.tsx
- frontend/src/components/scss/helpers.scss
- frontend/src/components/scss/nav.scss
- frontend/src/components/scss/variables.scss
base font-size from 18px -> 16px
> reduce font size

- .vscode/extensions.json
> Update vscode extension recommendations

- .env-example
- README.md
- backend/cli/__init__.py
- backend/cli/cmds.py
- tslint.json
also add cli command for just typechecking
> update readme with cli info

- backend/cli/__init__.py
- backend/cli/cmds.py
use subprocess.run when one process is selected
> fix(cli): test command

- poetry.lock
- pyproject.toml
This will fail a test if it exceeds a configured timeout.
> dep: add pytest-timeout

- backend/core/conftest.py
recipe_pie_facotry => recipe_pie_factory
> fix: typo in conftest function name

- frontend/src/api.ts
- frontend/src/classnames.ts
- frontend/src/components/AddRecipe.tsx
- frontend/src/components/MemberRow.tsx
- frontend/src/components/Owner.tsx
- frontend/src/containers/Team.ts
- frontend/src/store/mapState.ts
- frontend/src/store/reducers/calendar.ts
- frontend/src/store/reducers/invites.ts
- frontend/src/store/reducers/recipes.ts
- frontend/src/store/reducers/teams.ts
- frontend/src/store/store.ts
- frontend/src/store/thunks.ts
- frontend/src/utils/general.ts
- tslint.json
> Add lint to check for object index being possibly undefined

- frontend/src/components/Calendar.tsx
- frontend/src/components/Schedule.tsx
- frontend/src/components/scss/helpers.scss
Before we show the shopping list & recipe list. Now we only show the
schedule.
> ref(schedule): show schedule on mobile

- frontend/src/components/Calendar.tsx
- frontend/src/components/scss/helpers.scss
Introduce some wrapping to fix weird wrapping
> fix schedule nav controls at mobile breakpoint

- .vscode/settings.json
- tslint.json
tslint rule prevents tabnabbing with <a target="_blank">
> tools: update .vscode to use node_modules typescript & add tslint rule

- backend/cli/__init__.py
- backend/cli/config.py
- backend/pytest_plugin/plugin.py
- only set defaults if DEBUG=1
> Make default configuration able to overridden

- frontend/src/components/CalendarDayItem.tsx
we were only checking if past, not if past the end of the day.
> fix(schedule): moving schedule items from current day

- frontend/src/components/Calendar.tsx
- frontend/src/components/CalendarDay.tsx
- frontend/src/components/DatePickerForm.tsx
- frontend/src/components/MemberRow.tsx
- frontend/src/components/NotificationsDropdown.tsx
- frontend/src/components/Owner.tsx
- frontend/src/components/PasswordResetConfirmation.tsx
- frontend/src/components/RecipeList.tsx
- frontend/src/components/Schedule.tsx
- frontend/src/components/Sessions.tsx
- frontend/src/components/ShoppingList.tsx
- frontend/src/components/SocialAccountSettings.tsx
- frontend/src/components/TeamCreate.tsx
- frontend/src/components/TeamInvite.tsx
- frontend/src/containers/AddRecipe.ts
- frontend/src/containers/Home.ts
- frontend/src/containers/Login.ts
- frontend/src/containers/Nav.ts
- frontend/src/containers/OAuth.ts
- frontend/src/containers/OAuthConnect.ts
- frontend/src/containers/PasswordChange.ts
- frontend/src/containers/PasswordReset.ts
- frontend/src/containers/PasswordSet.ts
- frontend/src/containers/Settings.ts
- frontend/src/containers/Signup.ts
- frontend/src/containers/Team.ts
- frontend/src/containers/UserHome.ts
- frontend/src/store/reducers/recipes.test.ts
- frontend/src/store/reducers/recipes.ts
- frontend/src/store/thunks.ts
This helps differentiate between the side effect functions and normal Redux actions.
> ref(thunks): add `Async` suffix to thunks & funcs that call API

- .circleci/config.yml
- backend/Dockerfile-postgres
- backend/Dockerfile-prod
- backend/backend/middleware.py
- backend/backend/settings.py
- backend/backend/test_middleware.py
- docker-compose-deploy.yml
- nginx/Dockerfile
- nginx/nginx.conf
CHANGES
- NGINX healthcheck endpoint and Dockerfile config
- Django healthcheck endpoint and Dockerfile config
TODO
- add django healthcheck and docker config
- add healthcheck commands to CLI and call those
> add: create healthcheck endpoints and docker config

- backend/cli/__init__.py
Having the code pull the images is pointless as starting the containers
will automatically pull them
> remove(cli): pointless docker pull of images

- README.md
- design.dot
Also update design.dot with cloudflare
> update(docs): adjust readme example DATABASE_URL

- backend/django.Dockerfile
- base.Dockerfile
- frontend/react.Dockerfile
- nginx/nginx.Dockerfile
- pgdump/pgdump.Dockerfile
- postgres/postgres.Dockerfile
This ensures we don't get a change in the upstream unexpectedly.
> add: SHAs to dockerfiles

- frontend/src/components/CalendarDayItem.test.tsx
- frontend/src/components/CalendarDayItem.tsx
- frontend/src/components/__snapshots__/CalendarDayItem.test.tsx.snap
Migrated the component to styled components with a prop for visibility
> remove: extraneous cursor-pointer in CalendarDayItem

- backend/backend/settings.py
- backend/core/auth/permissions.py
- backend/core/auth/test_authentication.py
- backend/core/models.py
- backend/core/recipes/serializers.py
- backend/core/recipes/test_recipe_timeline.py
- backend/core/recipes/test_recipes.py
- backend/core/recipes/test_recipes_permissions.py
- backend/core/recipes/views.py
- backend/core/teams/test_teams.py
- backend/core/urls.py
- frontend/src/api.ts
- frontend/src/components/AddIngredient.tsx
- frontend/src/components/CalendarDayItem.test.tsx
- frontend/src/components/Home.test.tsx
- frontend/src/components/Recipe.test.tsx
- frontend/src/components/Recipe.tsx
- frontend/src/components/RecipeItem.test.tsx
- frontend/src/components/RecipeTimeline.tsx
- frontend/src/components/__snapshots__/Recipe.test.tsx.snap
- frontend/src/result.ts
- frontend/src/search.ts
- frontend/src/store/reducers/recipes.test.ts
- frontend/src/store/reducers/recipes.ts
- frontend/src/testUtils.tsx
- frontend/src/webdata.ts
- package.json
- tslint.json
- yarn.lock
Idea is that comments and similar will be incorporated into the view.
> add: timeline view for recipe of when it was scheduled in the past

- frontend/src/components/AddRecipe.test.tsx
- frontend/src/components/App.test.tsx
- frontend/src/components/LandingPage.tsx
- frontend/src/components/Nav.test.tsx
- frontend/src/components/OAuth.test.tsx
- frontend/src/components/PasswordReset.test.tsx
- frontend/src/components/Recipe.test.tsx
- frontend/src/components/Recipe.tsx
- frontend/src/components/Team.test.tsx
- frontend/src/components/TeamInvite.test.tsx
- frontend/src/components/__snapshots__/Recipe.test.tsx.snap
- frontend/src/containers/Login.test.tsx
- frontend/src/containers/Signup.test.tsx
- frontend/src/store/reducers/recipes.ts
- frontend/src/store/reducers/rootReducer.test.ts
- frontend/src/store/store.ts
- frontend/src/testUtils.tsx
- frontend/src/webdata.ts
Refactor usage of emptyStore to use a new function, createEmptyStore.
Passing around the one instance of emptyStore was harry since multiple
tests could access the same store.
> add: tests for Recipe.tsx and useRecipe hook

- frontend/src/components/Calendar.tsx
- frontend/src/components/CalendarDay.tsx
- frontend/src/components/scss/schedule.scss
- frontend/src/theme.ts
- package.json
- yarn.lock
Testing out styled-components on a some more complex use cases
> ref: calendar day & calendar styles to use styled-components

- frontend/src/components/Calendar.tsx
- frontend/src/components/__snapshots__/Calendar.test.tsx.snap
It now seems the Safari specific h-100 is now required in Chrome as well.
🤷‍♂️
> fix(schedule): style regression

- backend/core/recipes/views.py
- backend/core/serialization.py
Updated the serializer to follow
https://steve.dignam.xyz/2020/02/09/preventing-n-plus-one-queries/
fixing the failed tests along the way.
> fix: n+1 serializer mixin

- frontend/src/components/AddIngredientForm.tsx
Previously the form was focusing to the first ingredient rather than
the recipe title.
> fix: add recipe form focus

- backend/backend/authentication.py
- backend/backend/middleware.py
- backend/backend/settings.py
- backend/core/auth/test_authentication.py
- frontend/src/http.ts
- poetry.lock
- pyproject.toml
Instead of the middleware and its cookie, we can use the samesite cookie
setting.
> remove: csrf middleware

- .vscode/settings.json
vscode is intent on adding this setting.
> fix(tools): vscode eslint fix setting

- s/squawk.py
Also update the squawk version
> ref(CI): squawk.py to handle merged migrations & fix git command

- backend/entrypoint.sh
Need to `exec` gunicorn so the signals are passed properly.
> fix(deploy): gunicorn signals in django container

- README.md
Update the readme with another entry for prior art
> add(docs): prior art example

- frontend/src/components/UserHome.tsx
- frontend/src/hooks.ts
> add(ui): schedule preview to home page

- frontend/src/components/Base.tsx
- frontend/src/components/IngredientView.tsx
- frontend/src/components/ListItem.tsx
- frontend/src/text.test.ts
- frontend/src/text.ts
Convert unicode fractions to their ascii form.
Also fix minor styling issue with the browse page.
> add(ingredients): normalizing unicode fractions

- frontend/src/components/Markdown.tsx
- frontend/src/components/ShoppingList.tsx
- frontend/src/components/__snapshots__/ListItem.test.tsx.snap
- frontend/src/components/__snapshots__/Recipe.test.tsx.snap
rel: https://github.com/recipeyak/recipeyak/pull/622
rel: https://github.com/recipeyak/recipeyak/pull/617
> fix(ui): unit formatting in shopping list & overflow in notes

- README.md
> update(docs): add whisk to readme

- frontend/src/components/RecipeItem.test.tsx
- frontend/src/components/RecipeItem.tsx
- frontend/src/components/RecipeList.tsx
- frontend/src/components/TeamRecipes.tsx
- frontend/src/components/UserHome.tsx
- frontend/src/search.test.ts
- frontend/src/search.ts
> add better search panel

- frontend/src/search.ts
> sort archived recipes last in search dropdown

- netlify.toml
This is part of a test of using Netlify for UI preview environments
> add netlify for UI previews

- frontend/src/components/Recipe.tsx
On recipe page load we now update the recipe name
> add: automatically update recipe name in URL on load

- frontend/src/components/UserHome.tsx
> fix(ui): only show "by " when recipe has author

- .circleci/config.yml
- backend/django.Dockerfile
- backend/entrypoint.sh
- infrastructure/playbooks/deploy.yml
- nginx/nginx.conf
collect static no longer works now that we've removed the plugin
> fix(api): docker build

- frontend/src/components/Recipe.tsx
When a user tabs back to the recipe page, refetch the data.
> feat(recipes): refetch on focus change

- README.md
> update(docs): include a couple more alternatives in the README

- frontend/src/components/RecipeTitle.tsx
> fix(recipes): tag deletion

- README.md
Another recipe management site / app
> update(docs): add prior art / alternative to readme

- frontend/src/components/RecipeList.tsx
- frontend/src/components/UserHome.tsx
- frontend/src/search.ts
This feature doesn't really work with the new querying features, so I'm removing it.
> cut: "match on" info for querying

- frontend/src/components/RecipeItem.test.tsx
- frontend/src/components/RecipeItem.tsx
- frontend/src/components/RecipeList.tsx
- frontend/src/components/UserHome.tsx
- frontend/src/search.test.ts
- frontend/src/search.ts
> feat: show matches in search results again

- frontend/src/api.ts
- frontend/src/components/Recipe.tsx
- frontend/src/components/UserHome.tsx
- frontend/src/hooks.ts
- frontend/src/http.ts
- frontend/src/store/thunks.ts
- frontend/src/webdata.ts
We cache a lot of other views by using Redux. This change caches the schedule preview on the home page using some global state.
> feat(ui): cache schedule preview

- netlify.toml
- nginx/nginx.conf
This change will allow us to access the API via api.recipeyak.com.
> feat(api): support api.recipeyak.com

- frontend/src/api.ts
- frontend/src/components/Calendar.tsx
- frontend/src/components/RecipeList.tsx
- frontend/src/components/UserHome.tsx
- frontend/src/store/reducers/recipes.test.ts
- frontend/src/store/reducers/recipes.ts
- frontend/src/store/thunks.ts
Previously we would refetch recipes when we navigate from the homepage to schedule. Now we reuse what we have.
This Redux code is pretty crufty and complicated.
> fix(ui): don't fetch recipes multiple times

- frontend/src/hooks.ts
This hook wasn't rerendering when when the setState callback was called.
> fix(ui): useStateCached not rendering correctly

- backend/core/recipes/serializers.py
- frontend/src/components/AddRecipe.tsx
- frontend/src/components/Avatar.tsx
- frontend/src/components/Notes.tsx
- frontend/src/components/Recipe.tsx
- frontend/src/components/UserDropdown.tsx
- frontend/src/components/__snapshots__/Nav.test.tsx.snap
- frontend/src/components/__snapshots__/Recipe.test.tsx.snap
- frontend/src/search.test.ts
- frontend/src/store/reducers/recipes.test.ts
- frontend/src/store/reducers/recipes.ts
Future changes will add events for recipe creation, archive, unarchive, etc.
Before
After
> feat(ui): redesign notes into timeline

- backend/django.Dockerfile
This should fix the container build
> fix(api): docker file using wrong poetry version

- frontend/src/components/Recipe.tsx
- frontend/src/components/RecipeTitleDropdown.tsx
- frontend/src/components/__snapshots__/Recipe.test.tsx.snap
we pretty much never use the timeline, so let's hide it in the dropdown.
> ref(ui): move timeline select button

- .eslintrc.js
- frontend/scripts/start.js
- frontend/src/classnames.ts
- frontend/src/components/AddRecipe.tsx
- frontend/src/components/Buttons.tsx
- frontend/src/components/CalendarDay.tsx
- frontend/src/components/Notes.tsx
- frontend/src/components/Owner.tsx
- frontend/src/components/Recipe.tsx
- frontend/src/components/SocialAccountSettings.tsx
- frontend/src/store/thunks.ts
> fix(ui): calendar day color

- backend/core/recipes/views.py
This improves serialization from 1100ms to 125ms. Those numbers are best of three.
drf serialization
1088 ms
1101 ms
1229 ms
diy serialization
125 ms
175 ms
253 ms
> perf(api): use custom serialization for recipe list

- backend/core/models/user.py
- backend/core/recipes/views.py
- backend/core/settings.py
prefetch_related is _slow_. Using QuerySet.values speeds things up by not creating model objects and avoiding a lot of code. 1162ms to 186ms.
**Before**
1162 ms
1239 ms
1144 ms
**After**
202 ms
191 ms
186 ms
> perf(api): use QuerySet.values to improve performance

- backend/core/auth/registration/serializers.py
- backend/core/auth/registration/views.py
- backend/core/auth/serializers.py
- backend/core/auth/views.py
- backend/core/cumin/test_parsing.py
- backend/core/recipes/views.py
- backend/core/renderers.py
- backend/core/schedule/views.py
- backend/core/test_renderers.py
- poetry.lock
- pyproject.toml
**before**
99 ms, 70 ms, 83 ms
**after**
38 ms, 18 ms, 18 ms
> perf(api): use orjson to improve serialization performance

- frontend/src/components/scss/main.scss
Switch from a 50/50 split to a 1/3, 2/3 split.
> ref(ui): update ingredient layout, quantity smaller, name larger

- backend/core/recipes/__snapshots__/test_recipes.ambr
- backend/core/recipes/test_recipes.py
- backend/core/recipes/views.py
- package.json
- poetry.lock
- pyproject.toml
We were missing some keys which caused a glitchy recipe loading experience for timeline items. io-ts would have caught this early.
> fix(api): recipe list to include full timeline object

- frontend/src/components/Notes.tsx
- frontend/src/date.test.ts
- frontend/src/date.ts
I'm going to add a new formatDate function that will only include the current date
> ref(ui): formatDate -> formatDateTime

- .circleci/config.yml
- s/stop_ci_if_no_changes
It's not perfect, but should help a bit
> ref(ci): only run jobs when sub directory changes

- frontend/src/components/App.tsx
We have auth and stuff on the backend, but accessing when not authed
isn't a great UX
> fix(ui): ensure more routes aren't accessible when not logged in

- README.md
TandoorRecipes:
- proper modeling of units & ingredients (with aliases supported)
- best effort importer, does its best with some heuristics to parse
ingredients into quantity, unit, ingredient, note pairs
- see: https://github.com/TandoorRecipes/recipes/blob/8a99907a519d29c658f1d257b2ad6a54ab4d426e/cookbook/helper/recipe_url_import.py
- meal plans
- recipes are added to a plan by clicking on the schedule and using the
modal that pops up to select the recipe & adjust quantities, date, etc.
- supports drag and drop between days
- jump to date
- adding recipes to a shopping list is pretty manual, need to use a
context menu on each recipe in the menu
- doesn't work on mobile
copymethat:
- "master list" concept, sort of like weekly things you always get
- can have multiple, one for turkey …
> update(docs): include a couple more alternatives to the readme

- frontend/src/components/Schedule.tsx
- frontend/src/components/scss/schedule.scss
We never used it and it was confusing when it was accidentally triggered.
> ref(schedule): cut collapsible sidebar

- frontend/src/components/RecipeTitle.tsx
Tag creation was broken in 6b077a64043866fb87227692d4ab5501b7fd9668
> fix tag creation

- README.md
RecipeSage takes a different approach with shopping list categorizing:
https://github.com/julianpoy/RecipeSage/blob/9988084927a27b99d4dde036e39800dede8ff9e8/Backend/src/services/shopping-list-categorizer.js
They special case some things like canned goods and then use a list of
mappings for other ingredients.
> update(readme): add another alternative

- README.md
Some of the dates I wasn't sure about, so I put the start of the year. Other times guessed based on the domain name / web.archive.org.
> update(readme): add creation dates for alts

- backend/core/schedule/test_team_calendar.py
- backend/core/schedule/views.py
- frontend/src/api.ts
- frontend/src/components/CalendarDay.tsx
- frontend/src/components/CalendarDayItem.tsx
- frontend/src/components/CalendarDayItemModal.tsx
- frontend/src/components/Modal.tsx
- frontend/src/date.ts
Clicking a recipe in the schedule now opens a modal instead of the navigating to the recipe.
> add: reschedule modal for scheduled recipes

- frontend/src/components/CalendarDayItemModal.tsx
https://user-images.githubusercontent.com/1929960/174302609-50a9733e-2180-4068-8fca-e6be5f49972a.mov
> refactor schedule modal to make recipe navigation clearer

- frontend/src/components/App.tsx
- frontend/tslint.json
Using the learnings from https://steve.dignam.xyz/2022/07/15/scroll-restoration/ with a couple minor changes since we're using an older version of react router which has a slightly different API.
> fix(ui): scroll restoration

- .circleci/config.yml
- frontend/react.Dockerfile
UI container build was failing due to a node version mismatch.
> fix ui container build

- .circleci/config.yml
- frontend/react.Dockerfile
- frontend/vite.config.ts
didn't run the container build and it failed with a perms error
switch from circle ci to node docker image which is root, less perms issues to deal with :D
> fix ui ci build for real

- frontend/src/components/Notes.tsx
> improve image upload layout

- frontend/src/components/Notes.tsx
> preserve image order

- frontend/src/components/Notes.tsx
- frontend/src/components/Reactions.tsx
> add reaction popover button if there are note reactions

- frontend/src/pages/recipe-detail/Notes.tsx
- frontend/src/store/reducers/recipes.ts
Before this it would take two attempts to remove an image.
> fix image deletion glitching

- frontend/package.json
- frontend/src/components/Forms.tsx
- frontend/src/pages/index/UserHome.tsx
- frontend/src/pages/recipe-list/RecipeList.page.tsx
- frontend/src/utils/querystring.ts
- frontend/yarn.lock
Now we store the search in the URL so when you navigate backwards, we'll restore the user's query. You can also click outside the search box to cancel the search
https://user-images.githubusercontent.com/1929960/184919379-8176459b-6fe2-47d8-b0b9-0729cc8091c4.mov
> persist search in url from homepage

- frontend/.ignore
- frontend/src/pages/recipe-detail/MetaData.tsx
- frontend/src/pages/recipe-detail/RecipeTitle.tsx
ensure we also disable editing the title section when editing isn't enabled.
> fix(ui): edit mode title edits

- frontend/src/components/App.tsx
Something changed since #737 that broke scroll restoration.
For some reason the `useHistory` doesn't update when the action changes 🤷🏻‍♂️
> fix(ui); scroll restoration again

- README.md
> add(docs): more prior art

- frontend/src/components/Nav.tsx
- frontend/src/components/scss/helpers.scss
> fix(ui): replace recipeyak with home nav item

- backend/core/auth/registration/views.py
- backend/core/auth/views.py
- backend/core/export/views.py
- backend/core/teams/views.py
- backend/core/urls.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/tox.ini
I think it's easier to grep / figure out where things are coming from.
> ref(api): ban rel imports

- frontend/src/pages/recipe-detail/MetaData.tsx
- frontend/src/pages/recipe-detail/RecipeTitle.tsx
- frontend/src/pages/recipe-list/RecipeItem.tsx
- frontend/src/search.ts
- frontend/src/store/reducers/recipes.ts
Add a link to the detail page so clicking the author's name will open up the browse page with the search query prefilled to show all the author's recipes.
> add(ui): click from recipe detail author to list view filtered by author

- .circleci/config.yml
- backend/django.Dockerfile
I don't know what happened but for some reason CI started failing with some error about trying to build cryptography from source??
Docs and error message mention upgrading pip and that fixed it.
https://cryptography.io/en/latest/installation/
> fix(ci): api container build cryptography install problem

- backend/core/recipes/views/recently_created_recipes_view.py
- backend/core/recipes/views/test_recently_created.py
- backend/core/urls.py
- frontend/src/api.ts
- frontend/src/pages/index/UserHome.tsx
Show a recently created card on the home page along side the recently viewed and the schedule.
> add(ui,api): recently created recipes

- backend/core/cumin/quantity.py
- backend/core/cumin/test_quantity.py
some more parsing changes for the scraper
> fix(api): parsing `pinch of` and case insentive

- backend/core/cumin/quantity.py
- backend/core/cumin/test_quantity.py
add another alias for tablespoon to the parser
> fix(api): parse tbsp as tablespoon

- frontend/src/components/scss/helpers.scss
- frontend/src/pages/index/UserHome.tsx
Reduce the spacing between the sections & the search input
> ref(ui): reduce spacing on search page

- frontend/src/components/Footer.tsx
- frontend/src/components/scss/main.scss
- frontend/src/pages/recipe-detail/Notes.tsx
> fix(ui): improve print media on recipe detail

- frontend/src/pages/recipe-detail/RecipeDetail.page.tsx
- frontend/src/pages/recipe-detail/RecipeTitle.tsx
> add(ui): edit mode disable button

- frontend/src/components/Nav.tsx
We had a thing where the nav would collapse into a dropdown on mobile, but that's kind of annoying, so now it doesn't and the teams tab is hidden under the profile dropdown.
> ref(ui): update nav to expand on mobile

- frontend/src/components/Footer.tsx
- frontend/src/pages/recipe-detail/RecipeTitle.tsx
- frontend/src/pages/schedule/CalendarDayItemModal.tsx
refactor the calendar item modal to have small title fonts and smaller buttons
eventually we'll scrape bulma for something else, but that day is not today
> ref(ui): calendar item modal scale

- frontend/src/components/scss/helpers.scss
- frontend/src/pages/recipe-detail/Notes.tsx
- frontend/src/pages/schedule/CalendarDayItemModal.tsx
> refactor reschedule modal

- backend/pyproject.toml
- backend/recipeyak/api/serializers/recipe.py
- backend/recipeyak/api/test_reactions_view.py
Realized we weren't setting up the pydantic mypy plugin. Oops.
https://pydantic-docs.helpmanual.io/mypy_plugin/#configuring-the-plugin
rel: https://github.com/pydantic/pydantic/issues/2895
> fix(api): mypy cfg missing pydantic plugin

- frontend/src/components/App.tsx
I think this might fix the issue where the cache is disappearing
https://tanstack.com/query/v4/docs/plugins/persistQueryClient#options
> fix(ui): cache expiring issue

- frontend/package.json
- frontend/src/components/Markdown.tsx
- frontend/yarn.lock
https://github.com/remarkjs/remark-gfm of the many plugins https://github.com/remarkjs/remark/blob/main/doc/plugins.md#list-of-plugins -- only really want the auto linking
> add(ui): github flavored markdown

- frontend/src/pages/recipe-detail/ImageGallery.tsx
Now any click on left or right side of page works.
> fix on click navigation within gallery

- backend/recipeyak/jobs/backfill_image_placeholders.py
- backend/recipeyak/jobs/recipeyak-backfill_image_placeholders.service
Improve logging, fix systemd service so it actually runs.
> ref(api): update cron service

- frontend/src/components/Dropdown.tsx
- frontend/src/components/scss/ListItem.scss
- frontend/src/components/scss/Notification.scss
- frontend/src/components/scss/Recipe.scss
- frontend/src/components/scss/buttons.scss
- frontend/src/components/scss/main.scss
- frontend/src/components/scss/nav.scss
- frontend/src/pages/recipe-detail/Reactions.tsx
- nginx/404.html
rel: https://defensivecss.dev/tip/hover-media/
rel: https://steve.dignam.xyz/2022/11/19/cursor-pointer-user-select-none/
> fix(ui): disable hover for non-hover

- backend/poetry.lock
- backend/pyproject.toml
- backend/recipeyak/api/base/middleware.py
- backend/recipeyak/api/login_user_detail_view.py
- backend/recipeyak/api/login_user_detail_view_test.py
- backend/recipeyak/api/logout_user_detail_view.py
- backend/recipeyak/api/password_change_detail_view.py
- backend/recipeyak/api/register_user_detail_view.py
- backend/recipeyak/api/urls.py
- backend/recipeyak/django/settings.py
- backend/recipeyak/models/user.py
- convert remaining class based views to function based views
- remove Django all auth
> ref(api): convert remaining endpoints to func views

- frontend/src/components/Buttons.tsx
- frontend/src/components/ErrorBoundary.tsx
- frontend/src/components/scss/buttons.scss
- frontend/src/pages/login/Login.page.tsx
- frontend/src/pages/password-change/PasswordChange.page.tsx
- frontend/src/pages/password-reset-confirm/PasswordResetConfirm.page.tsx
- frontend/src/pages/password-reset/PasswordReset.page.tsx
- frontend/src/pages/recipe-create/RecipeCreate.page.tsx
- frontend/src/pages/recipe-detail/AddIngredientForm.tsx
- frontend/src/pages/recipe-detail/AddSectionForm.tsx
- frontend/src/pages/recipe-detail/AddStepForm.tsx
- frontend/src/pages/recipe-detail/ImageGallery.tsx
- frontend/src/pages/recipe-detail/Ingredient.tsx
- frontend/src/pages/recipe-detail/ListItem.tsx
- frontend/src/pages/recipe-detail/Notes.tsx
- frontend/src/pages/recipe-detail/Owner.tsx
- frontend/src/pages/recipe-detail/RecipeTitle.tsx
- frontend/src/pages/schedule/Calendar.tsx
- frontend/src/pages/schedule/CalendarDayItemModal.tsx
- frontend/src/pages/schedule/CalendarMoreDropdown.tsx
- frontend/src/pages/settings/Settings.page.tsx
- frontend/src/pages/signup/Signup.page.tsx
- frontend/src/pages/team-create/TeamCreate.page.tsx
- frontend/src/pages/team-detail/MemberRow.tsx
- frontend/src/pages/team-detail/TeamDetail.page.tsx
- frontend/src/pages/team-invite/TeamInvite.page.tsx
- frontend/src/pages/team-list/Invites.tsx
Use button components in the calendar item modal
Before:
After:
Also refactored the button components a bit.
> ref(ui): update calendar item modal to use buttons

- frontend/src/components/Buttons.tsx
- frontend/src/pages/recipe-list/RecipeList.page.tsx
- frontend/src/pages/team-detail/TeamDetail.page.tsx
Gradually componentizing things so we can avoid using `className` so much.
> ref(ui): allow using button component as link

- backend/s/db_download_backup
- frontend/src/utils/url.ts
blob URLs shouldn't be touched
> fix urls for imgix

- frontend/src/components/App.tsx
- frontend/src/components/ScrollRestore.tsx
This is probably the 3 or 4th attempt at fixing scroll restore at this point.
> fix(ui): scroll restore

- backend/recipeyak/api/calendar_generic_view_test.py
- backend/recipeyak/api/calendar_list_view.py
- backend/recipeyak/api/recently_created_recipes_view.py
- backend/recipeyak/api/recently_view_recipes_view.py
- backend/recipeyak/api/team_calendar_test.py
- backend/recipeyak/models/upload.py
- frontend/src/api.ts
- frontend/src/components/Box.tsx
- frontend/src/components/Image.tsx
- frontend/src/components/scss/helpers.scss
- frontend/src/pages/index/Index.page.tsx
- frontend/src/pages/index/UserHome.tsx
- frontend/src/pages/recipe-list/RecipeItem.tsx
- frontend/src/pages/schedule/Calendar.tsx
- frontend/src/pages/settings/Settings.page.tsx
- frontend/src/queries/authLogout.ts
- frontend/src/queries/userDelete.ts
- frontend/src/store/thunks.ts
- add images to home page panel lists
- move user delete to react-query
- fix logout to clear logged in setting
- shorten shopping to shop in calendar page
> add(ui,api): images for home page panels

- frontend/src/pages/schedule/CalendarDay.tsx
> fix(ui): wrong css background color

- frontend/src/pages/schedule/Schedule.page.tsx
rel: https://github.com/TanStack/query/issues/1858
> fix(ui): react useEffect infinite loop

- frontend/src/components/App.tsx
Now we restore _then_ render the UI
I tried show a loading indicating while hydrating but hydrating is quick enough that it looks glitchy
I think Linear must have some required time of $N milliseconds even if they are done restoring state.
> ref(ui): don't render while hydrating

- frontend/src/pages/index/UserHome.tsx
> fix(ui): round images homepage

- frontend/src/pages/schedule/Calendar.tsx
- frontend/src/pages/schedule/CalendarDayItem.tsx
- frontend/src/pages/schedule/HelpMenuModal.tsx
we shouldn't have been using toggle for the escape keypress callback
> fix(ui): modals showing when pressing escape

- backend/recipeyak/migrations/0109_auto_20230101_0030.py
> fix(api): backfill migration for personal teams

- backend/recipeyak/api/recipe_bot_detail_view.py
This should let us see more of our images when sharing via iOS
> make OpenGraph image preview larger

- frontend/src/api.ts
- frontend/src/pages/recipe-list/RecipeItem.tsx
- frontend/src/search.test.ts
- frontend/src/search.ts
Then we can trim the API response
> ref(ui): slim down the type for the recipe list

- frontend/src/pages/recipe-detail/RecipeDetail.page.tsx
> fix share via iOS

- backend/recipeyak/api/recipe_list_view.py
Pydantic's current behavior around nullable fields doesn't require passing them in, instead we have to use the `= Field(...)` syntax to make them required.
V2 fixes this:
https://github.com/pydantic/pydantic/issues/4887
https://docs.pydantic.dev/blog/pydantic-v2/#required-vs-nullable-cleanup
> fix(api): missing fields in recipe list view

- backend/recipeyak/jobs/backfill_image_placeholders.py
giving https://docs.sentry.io/product/crons/getting-started/ a spin
> add(api): sentry monitoring for cron

- backend/poetry.lock
- backend/pyproject.toml
- backend/recipeyak/api/calendar_list_view.py
- backend/recipeyak/api/serializers/recipe.py
- backend/recipeyak/models/__init__.py
now we use the Recipe.source for crediting the scraped images in the ui
> add(ui,api): authorship for scraped images

- backend/recipeyak/api/base/drf_json_renderer.py
- backend/recipeyak/api/team_shopping_list_detail_view.py
- frontend/src/api.ts
- frontend/src/components/App.tsx
- frontend/src/pages/schedule/ShoppingList.tsx
> add(ui): shopping list recipes in modal

- backend/recipeyak/api/team_shopping_list_detail_view.py
we were returning the scheduled recipe id instead of the recipe id. oops!
> fix(api): shopping list endpoint recipe id

- backend/recipeyak/scraper/__init__.py
allows parsing recipes that are missing `total_time`, `yields`, or `author`
> fix(api): handle more errors in scraper

- .circleci/config.yml
> ci: skip tests on master, only run builds

- frontend/src/pages/recipe-list/RecipeList.page.tsx
by using a search input we get the little `x` on the right side to make it easier to clear out the contents
not sure why we weren't using them before
> ui: text input to search input

- .circleci/config.yml
we don't need to be that careful, let's auto deploy
> ci: auto deploy

- frontend/src/components/CloseButton.tsx
- frontend/src/components/Modal.tsx
- frontend/src/components/scss/main.scss
- frontend/src/pages/recipe-detail/TagEditor.tsx
- frontend/src/pages/schedule/CalendarDay.tsx
- frontend/src/sass/base/generic.sass
- frontend/src/sass/components/modal.sass
- frontend/src/sass/elements/_all.sass
- frontend/src/sass/elements/other.sass
- frontend/src/sass/utilities/_all.sass
- frontend/src/theme.ts
- delete button not rendering properly
- hover / active state on mobile links
> ui: fix misc theme issues

- frontend/src/components/Image.tsx
- frontend/src/pages/recipe-detail/RecipeDetail.page.tsx
- use aspect-ratio for primary image on recipe detail
- remove margin from primary image sides on mobile
- remove border-radius from primary image sides on mobile
> ui: update recipe detail image to use aspect-ratio

- frontend/src/components/scss/inputs.scss
- frontend/src/components/scss/main.scss
- frontend/src/pages/index/UserHome.tsx
- frontend/src/pages/recipe-detail/RecipeTimeline.tsx
- frontend/src/pages/recipe-detail/ScheduleModal.tsx
- frontend/src/pages/schedule/CalendarDayItemModal.tsx
- frontend/src/pages/settings/Settings.page.tsx
- frontend/src/sass/base/generic.sass
- frontend/src/theme.ts
https://en.wikipedia.org/wiki/Solarized
also fixed some missing css var usage
> ui: add theme solarized

- frontend/src/components/App.tsx
- frontend/src/hooks.ts
- frontend/src/pages/settings/Settings.page.tsx
- frontend/src/queries/userFetch.ts
- frontend/src/theme.ts
still not perfect, need to preload index.html with user info & theme css classes to properly fix it
> ui: cache theme info

- frontend/src/components/Buttons.tsx
- frontend/src/components/Modal.tsx
- frontend/src/components/scss/main.scss
- frontend/src/pages/recipe-detail/Reactions.tsx
- frontend/src/pages/schedule/CalendarDayItem.tsx
- frontend/src/pages/settings/Sessions.tsx
- improve styling of disabled buttons
- make placeholder text more obvious
- fix background color of modals -- lighten it up a bit
- adjust margin of calendar item rows
- fix reaction backgrounds
> ui: misc theme / style cleanup

- frontend/src/pages/recipe-detail/RecipeDetail.page.tsx
- frontend/src/pages/recipe-detail/TagEditor.tsx
- fix spacing issue with tag editor
- fix primary image overlay not aligning with image
> ui: fix primary image edit overlay, tag editor

- frontend/src/pages/schedule/CalendarDay.tsx
when the shopping list creation modal is open we now highlight the calendar days that are being shopped for
> ui: fix calendar day selection when shopping

- frontend/src/pages/recipe-detail/Notes.tsx
- frontend/src/pages/recipe-detail/ScheduleModal.tsx
- fix schedule input on mobile (now expands to full width
- hide image upload progress bar
> ui: schedule input on mobile, progress bar

- frontend/src/components/scss/helpers.scss
- frontend/src/pages/recipe-list/RecipeItem.tsx
- frontend/src/pages/schedule/Schedule.page.tsx
- 300px to 250px width
- also adjust recipe item title line-height, a little closer
> ui: reduce schedule recipe list width

- frontend/src/auth.ts
- frontend/src/components/App.tsx
we weren't setting the theme after logging in so you'd be stuck on the default until you nav'd to the settings page
the way themes work still feels hacky
> ui: set theme on login

- frontend/src/components/App.tsx
really we need to server side render
> ui: fix theme again

- frontend/src/pages/recipe-detail/Notes.tsx
basically make loading a little nicer and mimic what we have on the home page.
> ui: add background for note images

- backend/recipeyak/api/user_detail_by_id_view.py
want to include all the types of recipes
> api: fix primary_photos_count query

- backend/recipeyak/api/user_detail_by_id_view.py
- frontend/src/pages/profile/Profile.page.tsx
- frontend/src/pages/recipe-detail/RecipeDetail.page.tsx
- frontend/src/queries/userById.ts
basic implementation that doesn't have pagination (limited to 42 rows)
also doesn't group by day or anything so gets a little noisy.
> profile: add activity timeline

- backend/recipeyak/api/user_detail_by_id_view.py
- backend/s/db_download_backup
- frontend/src/pages/profile/Profile.page.tsx
- frontend/src/queries/userById.ts
> profile: group days

- .github/workflows/ui.yml
having issues with nested package.json & yarn.lock + caching
> ci: hopefully fix javascript caching

- backend/recipeyak/api/user_detail_by_id_view.py
previously just picking 42 rows which doesn't really line up to full days
> profile: show 3 months of activity

- frontend/package.json
- frontend/src/components/Markdown.tsx
- frontend/yarn.lock
see: https://github.com/silvenon/remark-smartypants?tab=readme-ov-file and https://daringfireball.net/projects/smartypants/
> ui: convert to em dashes in markdown

- backend/poetry.lock
- backend/pyproject.toml
- backend/recipeyak/api/recipe_list_view.py
- backend/recipeyak/scraper/__init__.py
for example on:
https://cooking.nytimes.com/recipes/1015413-brandied-pumpkin-pie
> scraper: scrape ingredient groups

- frontend/src/pages/schedule/CalendarDayItemModal.tsx
add some buttons for the easy cases:
tomorrow, next week
might add more options later
> ui: refactor reschedule modal

- frontend/src/components/Buttons.tsx
- frontend/src/pages/schedule/CalendarDayItemModal.tsx
This reverts commit 4a1764e71f7a328d6e81ae381f0faa8a34b0a5f1.
> Revert "ui: adjust btn color in modal (#1124)"

- e2e/.gitignore
- e2e/package-lock.json
- e2e/package.json
- e2e/playwright.config.ts
- e2e/tests/authUtils.ts
- e2e/tests/modal-recipe-search.ts
- e2e/tests/page-add.spec.ts
- e2e/tests/page-calendar.spec.ts
- e2e/tests/page-home-page.spec.ts
- e2e/tests/page-landing-page.spec.ts
- e2e/tests/page-login.spec.ts
- e2e/tests/page-recipe-detail.spec.ts
we're not running them in CI since they use screenshots and are extra flakey but they could be useful when making changes to styling/components/etc
> e2e: add some playwright tests

- .vscode/settings.json
- e2e/tests/page-recipe-detail.spec.ts
- frontend/src/components/Avatar.tsx
- frontend/src/components/Nav.tsx
- frontend/src/pages/recipe-detail/AddIngredient.tsx
- frontend/src/pages/recipe-detail/AddStep.tsx
- frontend/src/pages/recipe-detail/ImageGallery.tsx
- frontend/src/pages/recipe-detail/Notes.tsx
- frontend/src/pages/recipe-detail/Reactions.tsx
- frontend/src/pages/recipe-detail/RecipeDetail.page.tsx
we're not running the e2e tests in CI, just using them as a before and after when making changes to the components to avoid any major regressions
> ui: more e2e tests and tailwind conversions

- frontend/src/pages/index/UserHome.tsx
Otherwise this looks weird on different themes
> use border color for <code/> border

- frontend/.eslintrc.cjs
- frontend/src/components/BorderBox.tsx
- frontend/src/components/Image.tsx
- frontend/src/components/scss/main.scss
- frontend/src/pages/recipe-detail/Reactions.tsx
- frontend/src/pages/recipe-list/RecipeItem.tsx
- frontend/src/pages/schedule/CalendarDay.tsx
- frontend/src/pages/schedule/ShoppingList.tsx
rel: https://github.com/tailwindlabs/tailwindcss/discussions/7044#discussioncomment-4697891
> ui: workaround tailwind bug with blur utils

- frontend/src/components/App.tsx
- frontend/src/pages/recipe-create/RecipeCreate.page.tsx
set in a useLayoutEffect to avoid flash
update styling of recipe create page
> ui: fix theme loading

- frontend/src/themeConstants.ts
> ui: adjust highlights

- .github/workflows/api.yml
Hopefully a cache can improve CI times
> cache python deps in CI

- frontend/index.html
I'll remove this from main if it doesn't work well
> add hacky theme

- frontend/index.html
This reverts commit 388470a5cd5b9a5f1cef67ac314a36bf9d8763d7.
> Revert "add hacky theme (#1164)"

- frontend/src/components/Modal.tsx
- frontend/src/pages/recipe-detail/ScheduleModal.tsx
> Make schedule modal mobile friendly

- frontend/src/components/scss/main.scss
- frontend/src/pages/schedule/CalendarDay.tsx
- frontend/src/pages/schedule/CalendarDayItem.tsx
> reduce calendar list item padding

- frontend/src/components/Nav.tsx
> remove extra nav padding on mobile viewport

- frontend/src/pages/recipe-detail/ScheduleModal.tsx
- frontend/src/pages/schedule/ScheduleRecipeModal.tsx
- don't disable schedule button
- make labels and button larger
> improve schedule modal

- .vscode/settings.json
- frontend/.eslintrc.cjs
- frontend/package.json
- frontend/src/components/App.tsx
- frontend/src/components/Forms.tsx
- frontend/src/components/RoatingLoader.tsx
- frontend/src/components/Table.tsx
- frontend/src/pages/schedule/ScheduledRecipeEditModal.tsx
- frontend/src/pages/settings/Sessions.tsx
- frontend/src/theme.ts
- frontend/tailwind.config.js
- frontend/yarn.lock
We're now only using tailwind and a bit of scss
> ui: remove the last of styled-components

- frontend/src/pages/recipe-detail/Notes.tsx
turns out you can't call useMutation.mutate in a loop and expect all the onSuccess and onError callbacks to fire -- feels like a bug
as a work around, we use mutateAsync instead
https://github.com/TanStack/query/issues/1573
> ui: fix file upload

- frontend/src/components/Avatar.tsx
- frontend/src/components/Buttons.tsx
- frontend/src/components/Modal.tsx
- frontend/src/pages/recipe-detail/Notes.tsx
- frontend/src/pages/recipe-detail/Step.tsx
- frontend/src/pages/schedule/ScheduledRecipeEditModal.tsx
Also fix double click / click events propagating up from the modal
> ui: rework schedule recipe edit modal

- frontend/src/components/Buttons.tsx
- frontend/src/components/Forms.tsx
- frontend/src/components/Markdown.tsx
- frontend/src/components/NavRecipeSearch.tsx
- frontend/src/pages/index/UserHome.tsx
- frontend/src/pages/recipe-detail/IngredientView.tsx
- frontend/src/pages/schedule/ScheduleRecipeModal.tsx
- frontend/src/url.ts
Used Github's search for inspiration.
Also adjusted some markdown styling.
Ran into some issues with safari where compositing and specifically the related paint were taking ages -- problem was we were rendering the multi-megabyte images in the search results instead of munging them into 100px ish images with imgix. After reducing the resolution, no more perf issues.
> ui: rework nav search

- frontend/src/components/Buttons.tsx
- frontend/src/components/NavRecipeSearch.tsx
use on keypress to better mimic input, use smaller icon on mobile to avoid overflow
> ui: update nav search

- frontend/src/components/Forms.tsx
- frontend/src/pages/schedule/Calendar.tsx
also fix bug with select box css
> ui: adjust calendar nav for mobile

- frontend/src/components/Markdown.tsx
- frontend/src/pages/recipe-detail/IngredientView.tsx
Basically so we can have links in ingredient descriptions that link to other recipes
In the future we can formalize the relation at the data level
> ui: support markdown in ingredient descriptions

- frontend/.eslintrc.cjs
- frontend/src/components/Markdown.tsx
- frontend/src/queries/cookChecklistUpdate.ts
- frontend/src/queries/inviteList.ts
- frontend/src/queries/recipeFetch.ts
- frontend/src/queries/scheduledRecipeCreate.ts
- frontend/src/queries/scheduledRecipeDelete.ts
- frontend/src/queries/scheduledRecipeList.ts
- frontend/src/queries/scheduledRecipeSettingsRegenerateLink.ts
- frontend/src/queries/scheduledRecipeSettingsUpdate.ts
- frontend/src/queries/sessionDelete.ts
- frontend/src/queries/sessionDeleteAll.ts
- frontend/src/queries/teamFetch.ts
- frontend/src/queries/teamMemberUpdate.ts
- frontend/src/queries/teamMembersList.ts
- frontend/src/queries/userFetch.ts
instead we should write type safe wrappers and call those
> ui: ban using react-query setQueryData directly

- frontend/src/components/NavRecipeSearch.tsx
- frontend/src/components/SearchInput.tsx
this mirrors what github does and avoids MacOS / iOS autocomplete messing up searching
idea cribbed from: https://interfaces.rauno.me
> ui: disable spellcheck and autocomplete for search inputs

- backend/recipeyak/api/base/router.py
- frontend/src/pages/schedule/CalendarDayItem.tsx
> ui: hack to fix drag and drop on desktop

- frontend/src/pages/schedule/CalendarDay.tsx
- frontend/src/pages/schedule/CalendarDayItem.tsx
migrate schedule drag and drop from react-dnd to react-aria's hooks
we can migrate the rest to react-aria later, the recipe detail still uses react-dnd for step, section, and ingredient reordering
> ui: fix drag and drop on schedule

- frontend/src/pages/schedule/CalendarDay.tsx
> ui: remove opacity on hover

- frontend/.eslintrc.cjs
- frontend/src/components/Buttons.tsx
- frontend/src/components/Modal.tsx
- frontend/src/components/NavRecipeSearch.tsx
- frontend/src/pages/recipe-detail/Notes.tsx
- frontend/src/pages/recipe-detail/RecipeTitleDropdown.tsx
- frontend/src/pages/recipe-detail/ScheduleModal.tsx
- frontend/src/pages/schedule/Calendar.tsx
- frontend/src/pages/schedule/CalendarDay.tsx
- frontend/src/pages/schedule/ScheduleRecipeModal.tsx
- frontend/src/pages/schedule/ScheduledRecipeEditModal.tsx
- frontend/src/pages/settings/ChangeTeam.tsx
- frontend/src/pages/settings/DangerZone.tsx
- frontend/src/pages/team-detail/Members.tsx
- frontend/src/pages/team-detail/TeamDetail.page.tsx
doesn't work in safari
https://steve.dignam.xyz/2024/01/24/confirm-not-working/
https://stackoverflow.com/questions/38083702/alert-confirm-and-prompt-not-working-after-using-history-api-on-safari-ios
> ui: fix confirm, prompt usage

- frontend/src/pages/user-comments/UserUploads.page.tsx
also tweak the spacing, haven't figured out how to best center it yet
> ui: fix typos in user upload page

- frontend/src/pages/user-comments/UserUploads.page.tsx
using js for now but I think we can do this all in css land
> ui: update profile images page to use full width

- infra/nginx/recipeyak.conf
can correlate nginx requests with django requests
> infra: log nginx requests with request_id

- frontend/src/components/Footer.tsx
- frontend/src/components/Nav.tsx
- frontend/src/pages/recipe-detail/Notes.tsx
we weren't clearing out the local versions of the uploads on save
> ui: fix upload leaving behind in memory images

- backend/recipeyak/api/calendar_update_view_test.py
- backend/recipeyak/api/cook_checklist_create_view_test.py
- backend/recipeyak/api/ingredient_create_view.py
- backend/recipeyak/api/ingredient_delete_view.py
- backend/recipeyak/api/ingredient_update_view.py
- backend/recipeyak/api/note_create_view.py
- backend/recipeyak/api/note_delete_view.py
- backend/recipeyak/api/note_update_view.py
- backend/recipeyak/api/reaction_create_view.py
- backend/recipeyak/api/reaction_delete_view.py
- backend/recipeyak/api/recipe_delete_view.py
- backend/recipeyak/api/recipe_update_view.py
- backend/recipeyak/api/section_create_view.py
- backend/recipeyak/api/section_delete_view.py
- backend/recipeyak/api/section_update_view.py
- backend/recipeyak/api/step_create_view.py
- backend/recipeyak/api/step_delete_view.py
- backend/recipeyak/api/step_update_view.py
- backend/recipeyak/conftest.py
- backend/recipeyak/models/note.py
- backend/recipeyak/models/recipe.py
- backend/recipeyak/realtime.py
- frontend/src/queries/recipeFetch.ts
This isn't the best way to do this, but it's quick
> refresh recipe on modification

- frontend/.eslintrc.cjs
- frontend/src/components/Checkbox.tsx
- frontend/src/components/DateInput.tsx
- frontend/src/components/EmailInput.tsx
- frontend/src/components/NavRecipeSearch.tsx
- frontend/src/components/PasswordInput.tsx
- frontend/src/components/RadioButton.tsx
- frontend/src/components/SearchInput.tsx
- frontend/src/components/TextInput.tsx
- frontend/src/pages/cook-detail/CookingFullscreen.tsx
- frontend/src/pages/recipe-detail/Notes.tsx
- frontend/src/pages/recipe-list/RecipeListSearch.tsx
- frontend/src/pages/schedule/ScheduledRecipeEditModal.tsx
cribbing what google has for their search input and login email inputs
> ui: disable more input features for search and email inputs

- backend/django.Dockerfile
- infra/deploy
- infra/systemd-services/recipeyak-algolia_sync.service
- infra/systemd-services/recipeyak-algolia_sync_continuous.service
- infra/systemd-services/recipeyak-backfill_image_placeholders.service
- infra/systemd-services/recipeyak-remove_old_checklists.service
also remove container health check since it doesn't really do anything
> infra: add names for background job containers

- backend/recipeyak/api/base/decorators.py
- backend/recipeyak/api/user_create_view_test.py
- backend/recipeyak/api/user_login_view_test.py
- backend/recipeyak/scraper/extract.py
- frontend/src/pages/recipe-detail/RecipeTitleDropdown.tsx
also fix archive modal cancel button
> api,ui: fix extracting amerciastestkitchen

- backend/recipeyak/api/base/codegen.py
we don't need to keep track of indentation since prettier handles that for us
we still include new lines in output because that results in a more readable output via prettier -- otherwise prettier keeps more things on a single line
> api: simplify codegen

- frontend/src/http.ts
when refactoring how exceptions are returned to the UI from the API the unauth flow was broken, oops
> ui: fix handling unauthed state

- backend/recipeyak/api/recipe_create_view.py
- backend/recipeyak/api/shoppinglist_retrieve_view.py
- backend/recipeyak/api/shoppinglist_retrieve_view_test.py
- backend/recipeyak/cumin/combine.py
- backend/recipeyak/cumin/combine_test.py
- backend/recipeyak/cumin/parsing.py
- backend/recipeyak/cumin/parsing_test.py
also rename from quantity to parsing for module and make stuff "private"
> api: fix parsing for cooks illustrated format

- backend/recipeyak/api/base/exceptions.py
- frontend/src/components/FormErrorHandler.tsx
- frontend/src/components/Page.tsx
- frontend/src/pages/signup/Signup.page.tsx
error responses are kind of a mess right now, probably use a helper or something in the future to help
> ui: fix signup error handling

- frontend/src/components/CloseButton.tsx
- frontend/src/components/Label.tsx
- frontend/src/components/Page.tsx
- frontend/src/pages/cook-detail/CookDetail.page.tsx
- frontend/src/pages/index/UserHome.tsx
- frontend/src/pages/login/Login.page.tsx
- frontend/src/pages/password-change/PasswordChange.page.tsx
- frontend/src/pages/password-reset-confirm/PasswordResetConfirm.page.tsx
- frontend/src/pages/password-reset/PasswordReset.page.tsx
- frontend/src/pages/profile/Profile.page.tsx
- frontend/src/pages/recipe-create/RecipeCreate.page.tsx
- frontend/src/pages/recipe-detail/RecipeDetail.page.tsx
- frontend/src/pages/recipe-list/RecipeList.page.tsx
- frontend/src/pages/schedule/Schedule.page.tsx
- frontend/src/pages/settings/Settings.page.tsx
- frontend/src/pages/signup/Signup.page.tsx
- frontend/src/pages/team-create/TeamCreate.page.tsx
- frontend/src/pages/team-detail/TeamDetail.page.tsx
- frontend/src/pages/team-invite/TeamInvite.page.tsx
- frontend/src/pages/team-list/TeamList.page.tsx
- frontend/src/pages/user-comments/UserComments.page.tsx
- frontend/src/pages/user-comments/UserUploads.page.tsx
refactor how we do titles so we can't as easily forget to add them
> ui: add titles to all the pages

- frontend/src/pages/login/Login.page.tsx
- frontend/src/pages/login/Login.test.tsx
- frontend/src/pages/password-change/PasswordChange.page.tsx
- frontend/src/pages/recipe-detail/AddIngredient.tsx
- frontend/src/pages/recipe-detail/AddSectionForm.tsx
- frontend/src/pages/recipe-detail/AddStep.tsx
- frontend/src/pages/recipe-detail/Ingredient.tsx
- frontend/src/pages/recipe-detail/Notes.tsx
- frontend/src/pages/recipe-detail/RecipeDetail.page.tsx
- frontend/src/pages/recipe-detail/Section.tsx
- frontend/src/pages/recipe-detail/Step.tsx
- frontend/src/pages/settings/ChangeEmail.tsx
- frontend/src/pages/settings/ChangeName.tsx
- frontend/src/pages/signup/Signup.page.tsx
instead of generic "save", be more specific
> ui: make form buttons more clear

- frontend/src/pages/recipe-detail/RecipeVersionModal.tsx
it's not perfect, but it's a start
> ui: recipe version modal support mobile

- frontend/src/pages/schedule/ScheduleRecipeModal.tsx
- frontend/src/pages/schedule/ScheduledRecipeEditModal.tsx
This reduces the image loading issue
> adjust image sizes for schedule modals

- backend/recipeyak/parsing.py
- backend/recipeyak/scraper/extract.py
- backend/recipeyak/string.py
- frontend/src/components/App.tsx
- frontend/src/text.ts
- don't include www. when rendering a website
- remove react query dev tools since we never use them
- adjust parsing to trim prefixes so we don't get "Servings Serves 4"
> ui/api: adjust parsing and source rendering

- frontend/src/components/scss/main.scss
stealing colors from instagram
> ui: darker dark mode

- frontend/src/components/CommandPalette.tsx
- frontend/src/components/NavRecipeSearch.tsx
- frontend/src/components/Page.tsx
- frontend/src/components/Palette.tsx
- frontend/src/components/SearchPalette.tsx
- frontend/src/input.ts
- frontend/src/pages/schedule/Calendar.tsx
- frontend/src/pages/schedule/HelpMenuModal.tsx
Also aligned the ui with the search input
> ui: add command palette

- backend/api-schema.json
- backend/recipeyak/api/base/serialization.py
- backend/recipeyak/api/calendar_settings_retrieve_view_test.py
- backend/recipeyak/api/note_create_view_test.py
- backend/recipeyak/api/recipe_create_view_test.py
- backend/recipeyak/api/user_update_view_test.py
- backend/recipeyak/models/ingredient_test.py
Inspired by https://brandur.org/disallow-unknown-fields / Stripe
> api: don't allow extra params

- frontend/src/pages/recipe-detail/RecipeTitleDropdown.tsx
> add icons to recipe detail action menu

- .vscode/extensions/recipeyak-dev/.vscode/launch.json
This only works if there aren't any editors open for recipeyak/
> open recipeyak/ folder when debugging extension

- frontend/package-lock.json
- frontend/package.json
- frontend/vite.config.ts
this is too complicated and not very useful
> remove sentry vite plugin

- frontend/src/pages/recipe-detail/RecipeDetail.page.tsx
need a better way to handle this, but for now just do this
> ui: fix archived banner z-index

- frontend/src/pages/recipe-detail/Section.tsx
- frontend/src/pages/recipe-detail/Step.tsx
> ui: adjust spacing with steps and sections

- frontend/package-lock.json
- frontend/package.json
this should hopefully fix the usePress issue we've seen: https://github.com/adobe/react-spectrum/issues/1513
> ui: upgrade react-aria-components to latest

- frontend/src/pages/schedule/CalendarDayItem.tsx
regression introduced by https://github.com/recipeyak/recipeyak/pull/1515
> ui: fix clicking calendar item
