frontend/src/components/scss/home.scss

The increased font size did not behave on <1080 monitors

Revert: font-size

---

frontend/.dockerignore
frontend/Dockerfile-prod
frontend/bootstrap.sh

Since we just use Javascript for building a bundle that we serve with
nginx, we don't actually need all the Javascript in the final release.
Our image size goes from 289MB => 8.76MB

Add docker builder pattern for react image

---

frontend/src/store/actions.js
nginx/nginx.conf

An interceptor triggers the SPA to do a full page reload when we recieve
a 503 from the API (maintenance status code)

Improve maintenance  mode

---

frontend/src/components/scss/main.scss
frontend/src/components/scss/variables.scss

Make text color black so it prints nicely. Gray doesn't behave with a
toner printer.
Add a grid-gap
Bump font-size

Update: css for recipe printing, larger font-size

---

frontend/src/components/UserHome.jsx

Now it always displays and more correctly states the current recipe
count, not the lifetime recipe added count.

Updated: userhome stat for user recipe count

---

frontend/config/webpack.config.dev.js
frontend/config/webpack.config.prod.js

Webpack deosn't like having extra args in its config setup so we have to
duplicate the faviconPath in dev and prod configs

Fix: broken webpack dev build

---

.circleci/config.yml
README.md
backend/Dockerfile-dev
backend/Dockerfile-prod

- Musl is slower than glibc and using slim provides a smaller image in practice
- Use same images across CI/Dev/Prod

Replace alpine with slim for Python

---

frontend/src/components/Calendar.jsx

Now we have month and year instead of month and day

Fix typo in calendar format string

---

.circleci/config.yml
backend/Pipfile.lock

- ~~CircleCI fails to build the Node container (I the process is possibly running out of memory)~~
- A service that caches layers between builds would be extremely useful
- Google Container Builder is an option, but it doesn't cache layers, just as CircleCI doesn't

Update circle config to build containers

---

frontend/src/components/App.jsx

We don't want the nav to render for the OAuth login page because it will
fail with a 403 and never retry.

Fix oauth login request issues

---

frontend/scripts/crawl.sh
nginx/nginx.conf

Update NGINX config to selectively route to pre-rendered homepage when
the user doesn't have a sessionid set in cookies. This prevents an
awkward flash of the landing page for users that already have an active
session.

Limit the pre-rendered homepage to users without a session id

---

backend/core/recipes/views.py

We weren't returning the owner field from the team endpoint. I'm not sure
why we had it this way, but now it behaves.

Fix scheduled recipes page rendering recipes list

---

frontend/src/store/actions.ts
frontend/src/uuid.ts

We introduced some bugs in d8dc53d474271288bec0b99ceb605832b6273f45. This
fixes an exception that is being raised when scheduling new recipes.

Fix exception from incorrect string conversion of uuid

---

frontend/src/store/reducers/calendar.ts

We now use pure numbers for our ids, so the string | number id we have
defined for ICalRecipe is unnecessary.

Remove unused toInt function in calendar reducer

---

frontend/src/store/actions.ts
frontend/src/store/reducers/recipes.test.ts
frontend/src/store/reducers/recipes.ts

We would redirect after deleting the recipe, but the recipe page would
lose its data and error before that could happen

fix deleting recipe bug

---

frontend/src/components/Calendar.tsx
frontend/src/store/reducers/calendar.ts

We were combining allIds by clearing byId, so indexing into byId from allIds
would return undefined. Now we concatenate byId and filter based on the current
team.

Fix bug where changing between views would break

---

backend/core/models.py
backend/core/recipes/serializers.py
backend/core/recipes/views.py
backend/core/serialization.py

Disable DB access in serializers to prevent N+1 queries.
Teams recipes list view performance
name | trial 1 | trial 2 | trial 3 | avg | % change
---|---|---|---|--- |---
before | 0.286s | 0.180s | 0.279s | 0.248s| —
after | 0.169s | 0.156s | 0.167s | 0.164s | -51.2%

Add prefetching to other recipe list view. Block DB access in serializers.

---

backend/core/auth/registration/serializers.py
backend/core/auth/serializers.py
backend/core/auth/social_serializers.py
backend/core/export/serializers.py
backend/core/export/views.py
backend/core/recipes/serializers.py
backend/core/schedule/serializers.py
backend/core/schedule/test_team_calendar.py
backend/core/schedule/views.py
backend/core/serialization.py
backend/core/teams/serializers.py
backend/core/teams/views.py
backend/core/users/serializers.py
frontend/src/store/actions.ts

N+1 queries are more of an issue with list views, so I think it's acceptable to
allow queries inside create views where we only serialize one object.

Restrict DB access in serialization

---

frontend/src/containers/AddRecipe.ts
frontend/src/store/reducers/addrecipe.ts

The AddRecipe form now uses the global team id state to update the team selection dropdown.

Use global team id in add recipe form

---

frontend/src/components/RecipeList.tsx
frontend/src/store/actions.ts
frontend/src/store/reducers/recipes.test.ts
frontend/src/store/reducers/recipes.ts
frontend/src/store/reducers/shoppinglist.ts
frontend/src/store/reducers/user.ts
frontend/src/webdata.ts
frontend/tslint.json

Refactor recipe Ids array in reducer so that we have separate arrays for each team. Personal recipes get their own array. We also setup the arrays to use `WebData<T>` and update the selectors accordingly.

refactor recipe ids

---

frontend/src/components/CalendarDay.tsx
frontend/src/components/CalendarDayItem.tsx
frontend/src/components/RecipeItem.tsx
frontend/src/dragDrop.ts
frontend/src/store/thunks.ts

Before:
We could only move scheduled recipes that aren't in the past
After:
We can now copy recipes from the past.

Add copying of past scheduled recipes

---

.circleci/config.yml
backend/Dockerfile-prod

When we updated our poetry version we neglected to update the versions
used in the backend Dockerfile and circleci jobs.

Fix poetry install for Dockerfile and CircleCI

---

frontend/config/webpack.config.prod.js

We already type check our TS code in another build job, so we can save
time by only transpiling the code via Webpack ts-loader.
We were having the same module resolution issue I solved by updating the
tsconfig.json, but it seems like Webpack ts-loader doesn't use that for
module resolution, so it was broken. It's possible to use the tsconfig
path settings for module resolution, but I think it's easier if we
ignore type checking all together for this container build.
Documentation on using baseUrl and paths settings from tsconfig.json:
https://github.com/TypeStrong/ts-loader/tree/58505c477669695655277dbd9aa538dc01374cc1#baseurl--paths-module-resolution

Fix webpack build for Typescript by disabled type checking

---

.circleci/config.yml

The `requires` key must be in the `jobs` subkey of `workflows`.
https://circleci.com/docs/2.0/workflows/#fan-outfan-in-workflow-example

Fix circleci config format

---

backend/backend/settings.py
backend/core/serialization.py

We were warning on all data accesses instead of database accesses. Now we only log a warning when a user attempts to access to the database.

Fix DB blocker to correctly warn about database access in serializers

---

frontend/src/components/Calendar.tsx
frontend/src/components/scss/helpers.scss

Doesn't occur in safari and firefox

Chrome would have the calendar overflow under the nav

---

backend/backend/settings.py

We were literally calling time.sleep in our tests

Disable dev middlewares for testing.

---

frontend/src/components/App.tsx
frontend/src/components/CurrentKeys.tsx
frontend/src/store/thunks.ts

Dragging a recipe while holding shift will duplicate it instead of
moving it.
Fix some weirdness around our optimistic scheduling of recipes.

Add shift to duplicate scheduled recipe

---

.circleci/config.yml

Caching was kind of busted by the introduction of the cli. This PR fixes that.
- cache yarn global cache
- correct caching for node_modules (this was accidentally broken when we reorganized the repo)
job | cached run time | no cache run time * | master run time with partial caching
--- | --- | ---| ---
frontend_test | 1:00 | 4:07 | 4:18
frontend_lint | 2:20 | 3:59 | 2:51
backend_test | 0:34 | 1:27 | 2:39
backend_lint | 1:11 | 2:00 | 3:26
\* this will only happen when we increment the cache versions. Typically we'll get a partial cache hit which should improve install performance.

improve caching

---

.vscode/settings.json

We weren't passing the config files in vscode correctly so flake8 and
mypy were silently failing

build: fix vscode config for mypy and flake8

---

.pylintrc

There are probably other pylint lints to ignore too, be we probably need
to be systematic to find them.

build: ignore formatting issues with pylint

---

poetry.lock
pyproject.toml

pytest-randomly will randomly order tests between each run. This can
help catch unintentional dependencies between tests.

add(test): pytest-randomly

---

tox.ini

When tests are starting, the first one can take a while to setup the
database connection

tools: bump test timeout

---

backend/cli/__init__.py

This is important for passing args to pytest, like `--testmon`

fix(cli): support passing unknown args to test command

---

.circleci/config.yml
backend/cli/__init__.py
backend/cli/config.py
backend/pytest_plugin/plugin.py
pyproject.toml

Loading the environment in pytest allows us to use the vscode python test discovery feature. Previously exceptions would be raised because the environment wasn't set correctly for plain calls to pytest.
This change also simplifies circleci and allows us to run our tests without a .env file.

Remove dependency on .env file for tests

---

.vscode/settings.json

The Microsoft language server is too unreliable to be useful. They've
introduced multiple regressions that make it basically useless. It seems
that Jedi works around all the issues I've found with the Microsoft
language server.

Replace Microsoft Python language server with Jedi

---

frontend/src/components/Calendar.tsx
frontend/src/components/scss/schedule.scss

previously had a limit that was causing text to overflow out of the
container

fix calendar day height

---

frontend/src/components/Calendar.tsx
frontend/src/components/RecipeItem.tsx
frontend/src/components/Schedule.tsx
frontend/src/components/ShoppingList.tsx
frontend/src/components/icons.tsx
frontend/src/components/scss/helpers.scss

- replace schedule button with drag handle. Schedule button isn't used but dragging isn't obvious.
- reduce padding on shopping list and decrease font size on shopping list
- make today button on schedule default instead of primary

ref(schedule): replace schedule button with drag handle for recipe item

---

backend/cli/__init__.py

we were overriding the DATABASE_URL in `.env` by calling load_dotenv()
after set_default_config()

fix(tools): loading of env vars

---

backend/cli/__init__.py

Before if we called `yak dev` without Postgres running we get some very
loud complaints from Django. Now we don't.

add: auto start postgres on `yak dev`

---

frontend/src/components/Calendar.tsx
frontend/src/utils/general.ts

Chrome 75 now results in the calendar scrolling.
Change h-100 to flex-grow but need to conditionally add h-100 for Safari.

fix(css): calendar page scrolling on Chrome 75

---

backend/core/auth/permissions.py
backend/core/schedule/test_calendar.py
backend/core/schedule/test_team_calendar.py
backend/core/schedule/views.py
backend/core/urls.py
frontend/src/api.ts
tox.ini

Now we just have `/t/:teamId/calendar` instead of an additional /calendar
endpoint.
A user's personal calendar can be queried with "me" as the teamId.

ref(api): combine team and personal calendar views

---

frontend/src/components/Calendar.tsx
frontend/src/store/reducers/calendar.test.ts
frontend/src/store/reducers/calendar.ts
frontend/src/store/thunks.ts
package.json

- Previously, when moving a calendar recipe away from its current day and
then back to its current day, the recipe would be deleted.
- fix issue when scheduling a recipe when one is already scheduled for a different team
- disable ts-jest diagnostics which break tests on typescript failures like unused imports

fix(calendar): moving cal recipe on same day

---

.circleci/config.yml

We didn't set the working_directory for the container build so COPY
wasn't working.

fix: pgdump container not building in CI

---

.circleci/config.yml

We had the working_directory appended in the build script when we are
already in it.

fix: building pgdump container

---

.circleci/config.yml
backend/django.Dockerfile
frontend/react.Dockerfile

we need to have the context be at the top level where we store the
pyproject.toml and yarn files.

fix: building of react & django containers in CI

---

pgdump/pgdump.Dockerfile

Previously we were just running apt-get install postgresql-client-10
instead of specifying. This downloaded the correct version locally but
failed to download the correct pgdump version on a different machine.
Now we specify the version according to the pg docs.

fix: pgdump install

---

.circleci/config.yml
backend/cli/__init__.py

We don't build or upload the container images via the CLI anymore
and the commands no longer work.
Let's just remove them.

remove: unused cli commands

---

frontend/src/components/AddIngredientForm.tsx

We now reset the focus to the first field on the add ingredient form after adding an ingredient.

fix: focus when adding ingredients in succession

---

backend/cli/__init__.py
frontend/src/components/CalendarDayItem.tsx
frontend/src/components/__snapshots__/CalendarDayItem.test.tsx.snap
frontend/src/theme.ts

The previous white was difficult to see against the primary orange
with f.lux running.

update: theme's white color to be less gray

---

frontend/src/components/IngredientView.test.tsx
frontend/src/components/IngredientView.tsx
frontend/src/components/ListItem.test.tsx
frontend/src/components/ListItem.tsx
frontend/src/components/__snapshots__/IngredientView.test.tsx.snap
frontend/src/components/__snapshots__/ListItem.test.tsx.snap
frontend/src/text.ts

teaspoon and tablespoon are less easy to mix up with they have distinct
casing that is always enforced.

add: auto casing for teaspoon & tablespoon

---

frontend/src/api.ts
frontend/src/components/Calendar.tsx
frontend/src/date.test.ts
frontend/src/date.ts
frontend/src/store/thunks.ts
frontend/src/testUtils.tsx
package.json
yarn.lock

Our previous implementation of `toISODateString` was bugged in that calling it on its output would result in the date shifting back a day. This only occurred in non-UTC environments so it wouldn't appear in tests since we set the env TZ to UTC.
TL;DR: `parseISO("2019-11-09") !== new Date("2019-11-09")`
rel SO Answer: https://stackoverflow.com/a/31732581/

fix: off-by-one error in optimistic scheduling

---

backend/core/renderers.py
backend/core/test_renderers.py

Previous `.normalize()` setup removed trailing zeros but it had the
unwanted side effect of formatting `250` as `2.5E+2`.
Now we use the solution recommended in the std lib decimal docs.

fix: decimal fmt in json encoder

---

frontend/src/urls.test.ts
frontend/src/urls.ts

We were dropping ù instead of replacing it with u

fix: ù in slugify

---

backend/core/cumin/__init__.py
backend/core/cumin/test_parsing.py
backend/core/renderers.py
backend/core/schedule/test_shopping_list.py
backend/core/test_renderers.py
frontend/src/api.ts
frontend/src/components/ShoppingList.test.ts
frontend/src/components/ShoppingList.tsx

Previously we were largely ignoring unknown units which wasn't great as
the rendered shopping list had some gaps.
Ideally we'd have the ingredients be something like
```
enum Unit {
TABLESPOON,
// ...
UNKNOWN(String)
}
```
But alas, we can't easily achieve that so instead we add a `unknown_unit`
field to the Quantity() which is nullable.
Also round decimals to prevent issues with combining resulting in:
`6.500000000000000000000000002` Tablespoons

add(cumin): better handling of unknown units

---

frontend/src/api.ts
frontend/src/components/Calendar.test.tsx
frontend/src/components/Calendar.tsx
frontend/src/components/__snapshots__/Calendar.test.tsx.snap
frontend/src/components/__snapshots__/Recipe.test.tsx.snap
frontend/src/store/reducers/calendar.test.ts
frontend/src/store/reducers/calendar.ts
frontend/src/store/thunks.ts
frontend/src/webdata.ts

Previously, we wouldn't fetch the next week when the date rolled over.
This meant the UI would show the next week but it wouldn't have any data.
Now we re-fetch the calendar data when the current week changes.
There are some foot guns related using `Date` in a React.useEffect
dependency array so we've changed some of the function return types and
args to use `number` instead of `Date`.
```
new Date("1776") !== new Date("1776")
```
while
```
new Date("1776").getTime() === new Date("1776").getTime()
```

add(calendar): auto fetching on week change

---

backend/core/cumin/__init__.py
backend/core/cumin/test_parsing.py

Previously we weren't parsing `oz` as ounce and we weren't handling
cases where quantities are combined, e.g., `4 ounces/112 grams`.

fix(cumin): parsing of `oz` as ounce and quantities that are combined

---

frontend/src/api.ts
frontend/src/components/Calendar.tsx
frontend/src/hooks.ts
frontend/src/store/reducers/calendar.test.ts
frontend/src/store/reducers/calendar.ts
frontend/src/store/thunks.ts

If a tab has been open for a while it's nice if when you come back to it
the data is updated.
Removed the unnecessary `allIds` field.
Made sure to handle deletions by clearing the range of calendar
items that the successful fetch covered.

add(schedule): refetch on focus change

---

frontend/src/hooks.ts

There's a bug in webkit so sometimes multiple window focus events get
created.
https://bugs.webkit.org/show_bug.cgi?id=179990

fix: focus event handler triggering multiple times in safari

---

frontend/src/components/Dropdown.tsx

Turns out that `close` is a global
https://developer.mozilla.org/en-US/docs/Web/API/Window/close
similar to the annoying `name`.
Would have been prevented by something like:
https://eslint.org/docs/rules/no-restricted-globals
This resulted in some buggy behavior where clicking on a nav button
would cause a full page reload instead of a smoother react based name.

fix(ui): unintended global usage

---

backend/core/conftest.py
backend/core/recipes/test_recipes.py
backend/core/recipes/views.py
backend/core/serialization.py
backend/core/teams/test_teams.py
backend/core/test_serialization.py

Turns out the wrappers passed to connection.execute_wrappers are expected
to call the `execute` arg and return its value.
https://docs.djangoproject.com/en/dev/topics/db/instrumentation/#connection-execute-wrapper
We were returning None and this resulted in some strange errors with django.
```
Traceback (most recent call last):
File "/root/.cache/pypoetry/virtualenvs/backend-py3.7/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 164, in __get__
rel_obj = self.field.get_cached_value(instance)
File "/root/.cache/pypoetry/virtualenvs/backend-py3.7/lib/python3.7/site-packages/django/db/models/fields/mixins.py", line 13, in get_cached_value
return instance._state.fields_cache[cache_name]
KeyError: 'last_modified_by'
```

fix: n+1 serializer mixin type error

---

frontend/src/text.test.ts
frontend/src/text.ts

We were only doing a singular replace across steps & ingredients instead
of all occurrences.

fix: capitalization for units

---

frontend/src/components/RecipeList.tsx

We remove the search query on load for the calendar, but we were using
`push` instead of `replace`. This meant it would take 2 navigations back
instead of the expected 1.

fix(calendar): extra browser history item due to search clearing

---

frontend/src/components/Markdown.tsx
frontend/src/components/__snapshots__/ListItem.test.tsx.snap
frontend/src/components/__snapshots__/Recipe.test.tsx.snap

We didn't initially include `ol` and `ul` in markdown. They can be handy
for some cases so let's enable them.

add(recipe): markdown list items for steps & notes

---

nginx/nginx.conf

For static files we use nginx's `expires: max;` to ensure the
browser can cache the files indefinitely.
With the index.html we don't want the browser caching since
the index contains references to the latest static files. If we let the
browser cache it via its heuristic then when we release a new version
the browser might not fetch it. Meaning the user could get stuck on an
older version for a bit.
rel: <http://nginx.org/en/docs/http/ngx_http_headers_module.html#expires>
rel: <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Preventing_caching>
rel: <https://paulcalvano.com/index.php/2018/03/14/http-heuristic-caching-missing-cache-control-and-expires-headers-explained/>

add(nginx): disable caching index.html

---

nginx/general_headers.conf
nginx/nginx.Dockerfile
nginx/nginx.conf

Turns out `add_header` removes all headers defined in the parent scope.
Now wherever we add a new header, we include the `general_headers.conf`
which includes the security headers with the response id and response
time.
rel: https://www.peterbe.com/plog/be-very-careful-with-your-add_header-in-nginx

fix(nginx): missing security headers

---

backend/backend/settings.py

Django requires setting SESSION_COOKIE_SECURE = True to make cookies
require HTTPS.
https://docs.djangoproject.com/en/2.2/ref/settings/#session-cookie-secure

update: session cookies to be secure

---

.circleci/config.yml

If the lock files are equivalent for two runs of CI, then their deps
should be equivalent.
rel: https://github.com/chdsbd/kodiak/pull/353

update(tools): circle ci config to not cache based on branch

---

backend/core/cumin/__init__.py
backend/core/cumin/test_parsing.py

Some recipes will give ranges with syntax like `3-5` or `4 to 6`. While
we don't support ranges in the ingredient model right now we can still
parse these and take the largest value.

update(cumin): quantity parsing with `3 to 6` case

---

frontend/src/components/Calendar.tsx
frontend/src/components/Nav.tsx
frontend/src/containers/AddRecipe.ts
frontend/src/store/reducers/teams.test.ts
frontend/src/store/reducers/teams.ts

Previously we had a `loading: boolean` for the teams info which meant
that even if the UI was refetching the data, it would show loading.
Now we have a more descriptive type so we show the stale data while we
refetch.

add: webdata style type for teams

---

backend/core/ical/test_ical_views.py
backend/core/ical/views.py

We were using DRF for this endpoint which didn't like it when iOS sent
a request with an accept header set to `text/calendar` and returned a
406. This meant adding calendars on iOS would fail.
Easy enough fix, don't use DRF, use plain Django.
Also update the endpoint to allow HEAD requests.

fix(ical): support subscribing to calendars on iOS

---

s/squawk.py

When merging to master CI runs again and the git command to fix Circle's
clobbering of the master ref fails.
Now we'll only run that when we aren't on master.
Kodiak also needs to be updated.

fix(squawk): setup to skip error when run on master

---

frontend/src/components/AddRecipe.tsx
frontend/src/components/Ingredient.tsx
frontend/src/components/Recipe.tsx
tslint.json

This is in preparation for adding positioning & drag and drop to
ingredients along with sections. The hooks api for React DND is much
nicer to work with.
I also changed the export from a default to a named export.
Also disable the tslint rule since `type` has inferred index signatures
making it support more features than interface.

ref(ui): ingredient component to use hooks

---

backend/core/recipes/test_recipes.py
frontend/src/components/AddRecipe.tsx
frontend/src/components/Ingredient.tsx
frontend/src/components/IngredientView.test.tsx
frontend/src/components/IngredientView.tsx
frontend/src/components/Recipe.tsx
frontend/src/components/Step.tsx
frontend/src/components/StepContainer.tsx
frontend/src/components/__snapshots__/Recipe.test.tsx.snap
frontend/src/dragDrop.ts
frontend/src/position.ts
frontend/src/store/reducers/recipes.ts

There was already a position field so this adds the UI to change that
field via drag and drop.
We do something similar with the recipe steps.
Didn't do the string based ordering, although we might want it when we
add sections.
rel: https://github.com/recipeyak/recipeyak/pull/130
rel: https://steve.dignam.xyz/2020/03/31/practical-ordering/

add(ui): drag and drop for reordering ingredients

---

.circleci/config.yml
frontend/s/build
frontend/s/lint
frontend/s/test
frontend/s/typecheck

We need to update nodejs for the eslint upgrade but that is more
complicated than it should be because we're using the python cli for
frontend related tasks.
In another PR we can remove the frontend portion of the cli.

ref(frontend): scripts to use bash instead of python cli

---

frontend/src/components/MetaData.tsx
frontend/src/components/__snapshots__/Recipe.test.tsx.snap

Previously, clicking on the link would open the edit mode while the
browser transitions you to the link's source.
Now we don't handle the click, so the edit panel isn't opened.

fix(ui): clicking on recipe source link opening edit mode

---

frontend/src/components/Notes.tsx

Update the created_at time for notes in the UI to have a title property
with the date the note was created.
Helps make the distance times of 3 months ago more clear.

add(ui): precise date as title to note humanized time

---

frontend/src/components/CalendarDayItem.tsx
frontend/src/components/__snapshots__/CalendarDayItem.test.tsx.snap

We were depending on the mouseEvent and mouseLeave events to fire to
keep track of the hover state for scheduled recipes.
This works okay when deleting a single item as when you drag your mouse
over to the item, the onMouseEnter handler fires.
However, when you have a couple items on the same day and delete the
first one, the next item will move up in the calendar day and the event
handlers won't fire. So the component will have its hover state set to
false when we are in fact hovering.
Instead of keeping track of hover state ourselves, we instead query the
DOM with `.matches()`
https://developer.mozilla.org/en-US/docs/Web/API/Element/matches

fix(ui): hover handling for calendar items

---

frontend/src/components/Markdown.tsx
frontend/src/components/Notes.tsx

Enable links as valid types in the markdown renderer.
Handle the case when a user clicks a link in the markdown component such
that we don't open edits.

add(ui): links in notes

---

frontend/src/components/Notes.tsx
frontend/src/components/scss/helpers.scss

On component mount we check if the hash is equal to the note id, if it
is we add the class to highlight the comment.
Initially tried using a `:target` pseudo selector approach but that
didn't end up working because we aren't SSR so we have a spinner and
the browser doesn't highlight the `:target` if it isn't initially in
the html it seems.

add(ui): linking directly to notes in recipes

---

backend/core/models.py
poetry.lock
pyproject.toml
tox.ini

Now we disable ignore_missing_imports globally and enable it on a pkg
by pkg basis.

tools(mypy): pkg level ignore_missing_imports

---

backend/backend/settings.py

We run the django server behind nginx so to get the require.is_secure
to work we have to configure the forwarded header.

fix: request.is_secure returning incorrect info due to proxy

---

frontend/src/components/Section.tsx

Changing this to be bold so the section stands out more, especially
on mobile. fw-500 was too small.

ref: ingredient section font weight

---

pyproject.toml

rel: https://github.com/chdsbd/kodiak/pull/519

fix(ci): pip fails to install pkgs with missing setuptools

---

frontend/src/components/Markdown.tsx
frontend/src/components/__snapshots__/ListItem.test.tsx.snap
frontend/src/components/__snapshots__/Recipe.test.tsx.snap
frontend/src/settings.ts

Use react-router links for URLs that reference app so you do nicer react
re-renders, instead of full page reloads.
Also render `https://recipeyak.com/recipes/17-potato-stew/` as
`recipes/17-potato-stew`.

ref(markdown): render in app links with react-router links

---

frontend/src/components/Markdown.tsx
frontend/src/components/__snapshots__/ListItem.test.tsx.snap
frontend/src/components/__snapshots__/Recipe.test.tsx.snap

Enable `blockquote`s via react-markdown.
Also add margin to space out the paragraphs. Mindful not to mess up the
block quotes

add(ui): block quotes and paragraph spacing for notes markdown

---

frontend/src/components/RecipeItem.tsx

Before only a recipe title could be click in the browse view, now the entire recipe item can be clicked.

add: larger recipe click targets for browse view

---

frontend/src/components/AddRecipe.tsx

If a step or ingredient is unsaved, but non-empty, save it anyway.

add(ui): save steps and ingredients if they are non-empty

---

frontend/src/components/Nav.tsx
frontend/src/components/__snapshots__/Nav.test.tsx.snap

The header was broken in Safari (not Chrome though) because of #607.

fix(ui): header in safari

---

.circleci/config.yml

Use `find` instead of `fd` since `fd` isn't installing.

fix(CI): docker lint failing due to fd-find not installing

---

frontend/src/components/CalendarDay.tsx
frontend/src/components/CalendarDayItem.tsx
frontend/src/components/Markdown.tsx
frontend/src/components/Recipe.tsx
frontend/src/components/RecipeTitle.tsx
frontend/src/components/RecipeTitleDropdown.tsx
frontend/src/components/__snapshots__/ListItem.test.tsx.snap
frontend/src/components/__snapshots__/Recipe.test.tsx.snap
frontend/src/date.ts
frontend/src/store/thunks.ts

Allow users to change the past 5 days of scheduling history. Helpful when
you made something, or didn't make something and want to change it.
Fix text wrapping bug with long links in markdown.
Move recipe deletion to the "options" dropdown where the archive button
is located.

ref(ui): allow changing a little bit of scheduling history

---

frontend/src/components/Markdown.tsx
frontend/src/components/__snapshots__/ListItem.test.tsx.snap
frontend/src/components/__snapshots__/Recipe.test.tsx.snap

Break all wraps links correctly, but messes with normal text.

revert(ui): break-all in markdown

---

frontend/src/http.ts

This timeout isn't helpful because on poor connections it will take a while for the API requests to be received. Timeouts matter on the backend.

cut(ui): timeout for api requests

---

frontend/src/components/Notes.tsx
frontend/src/components/Sessions.tsx
frontend/src/date.ts

Due to clock skew, timestamps would sometimes be formatted as a distance
into the future.
Now we cap the dates to `now()` to avoid `in a few minutes` style
messages.

fix(ui): clock skew with timestamp distance formatting

---

frontend/src/store/thunks.ts

This allows for a nicer pagination experience because the recipes for the next pages will already be loaded.

fetch wider window for calendar page

---

frontend/src/components/RecipeList.tsx
frontend/src/utils/querystring.test.ts
frontend/src/utils/querystring.ts

Previously on load we deleted the entire URL search. This broke navigation so you couldn't visit a recipe and return to your place in the calendar, because the "week" parameter would be removed on load.
Now we only remove specific keys from the query string: "recipeId" and "search"

fix recipe list to only remove specific search params

---

netlify.toml

Netlify doesn't support full regex like NGINX, so we need to more more explicit in our redirects. Netlify only supports the `*` operator at the end of a URL.
This change fixes our Netlify config to allow `/recipes.json` and `/recipes/435.json` to work.

fix(ui): netlify redirects

---

frontend/src/store/reducers/recipes.test.ts
frontend/src/store/reducers/recipes.ts

Previously tabbing away from the page while editing a new note would clear the note editor when you tabbed back. This was because the creatingNewNote field was being removed by the refetch of the recipe on window focus change.
Now we preserve the creatingNewNote data between fetches.

fix: tabbing disabling note editing

---

frontend/src/components/Recipe.tsx

Previously if you clicked an outgoing link on the recipe page, you would see a momentary 404 before the browser redirected to the URL. This only affected iOS.
Now we only update the recipe URL if the hostname is recipeyak or localhost.

fix(ui): 404 on outgoing navigation

---

frontend/src/components/MetaData.tsx

Previously we would try to incorrectly render a plain text source as an anchor tag. Now we only render a URL as an anchor tag.

fix(ui): non-url source rendering in Recipe title

---

frontend/scripts/start.js
frontend/src/components/Recipe.tsx
frontend/src/store/reducers/recipes.ts

There's been this persistent issue on iOS since we added more network
requests to sync the recipe data.
When naving away there will be an infight network request due to some
onfocus handlers, this network request gets killed by the browser with
an error: NetworkError
This was surfaced in the UI as a 404.
Now we return early from the network request. Really we want to show an
error unless a previous network request has succeeded, but
this is fine for now.

fix(ui): error w/ inflight request while naving to diff hostname on iOS

---

frontend/src/components/Notes.tsx

We were accidentally clearing the edited text of a note on rerender.

fix(ui): note rendering wiping edited text

---

backend/core/export/test_export.py
backend/core/response.py

Pyyaml was garbling unicode chars in the exports

fix(api): pyyaml unicode encoding issues

---

frontend/src/components/CalendarDayItem.tsx
frontend/src/components/__snapshots__/CalendarDayItem.test.tsx.snap
frontend/src/theme.ts

Black text and a white background is more legible than the previous orange background and white text.

feat(ui): change calendar item color

---

backend/core/recipes/test_recipes.py
backend/core/settings.py

We removed the cache middleware back in 6fc14b469d7eaf80a7d083e209fb50b0a3d76bb6
which was a mistake.
I thought about adding these headers in nginx, but it's kind of a pain
to test and this will also apply in dev which is nice.

fix(api): don't cache api responses

---

backend/core/middleware.py

This should prevent any confusion during local dev

feat(api): add sentry span for api delay middleware

---

.vscode/settings.json

We should use Pylance, not Jedi. We also don't use pylint.

fix(tools): vscode config

---

frontend/src/components/IngredientView.tsx

Now we properly capitalize units in ingredient descriptions.

fix(ui): format ingredient description units

---

frontend/src/components/Recipe.tsx
frontend/src/components/scss/helpers.scss

Looks better when we squish the page to 1000px wide instead of ~1500px

ref(ui): update recipe detail to less wide

---

frontend/src/components/Recipe.tsx
frontend/src/date.ts

This is like the formatDateTime, but includes only the date portion. Relative dates say "Today" instead of "10 minutes ago"

update archived marker to use nicer date format

---

frontend/src/components/App.tsx
frontend/src/components/Footer.tsx
frontend/src/components/Invites.tsx
frontend/src/components/Nav.tsx
frontend/src/components/Teams.tsx
frontend/src/components/scss/ListItem.scss
frontend/src/components/scss/helpers.scss
frontend/src/containers/Team.ts

We hardly ever use these so might as well hide them away.
The new and existing teams related pages are really crufty, but we never use them so fine for now.

ref(ui): hide team list & team invites behind a dropdown in the nav

---

frontend/src/browser.ts
frontend/src/components/Ingredient.tsx

Find On Page in Safari for iOS won't find text that is inside an element
marked `draggable="true"`
Since the current drag and drop doesn't work on iOS, we disable it entirely
to prevent writing the `draggable` prop.
https://bugs.webkit.org/show_bug.cgi?id=234716
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable

fix(ios): Find On Page not working for ingredients

---

backend/core/recipes/test_recipes.py
backend/core/recipes/views.py

This was causing a flash when loading a recipe after viewing the recipe list view. The "created" and "archived" timeline views would start with null users and then flash with the actual user after loading the detail view.
io-ts would have prevented this nonsense.

fix incorrect object serialization for timeline items

---

frontend/src/components/CalendarDay.tsx
frontend/src/components/CalendarDayItem.tsx
frontend/src/components/CalendarDayItemModal.tsx

We were using the scheduled item ids instead of the recipe ids.
Many 404s were had, whoops!

fix(ui): calendar modal ids

---

frontend/src/components/CalendarDayItem.tsx

Instead of opening the modal, they'll use the default browser behavior.

fix(ui): shift & command clicking cal recipe links

---

frontend/.eslintrc.js

Ensure VSCode doesn't try to look for tsconfig.json in the directory of the component you're viewing.
https://stackoverflow.com/a/66088074/3720597

fix(ui): eslint config rel path issue

---

.vscode/settings.json

VSCode was using relative paths for the tox.ini config file, so opening vscode at the root of the repo wouldn't work -- we'd get a ton of flake8 errors that we've already ignored.

fix(api): vscode flake8 errors

---

frontend/src/components/RecipeItem.tsx

We're hitting https://github.com/react-dnd/react-dnd/issues/3345#issuecomment-1105475910 with the drag and drop dropEffect.
https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect
Easy enough to remove the options, they didn't seem to do anything anyways.

ui(schedule): workaround react-dnd bug

---

frontend/src/components/Notes.tsx

During the upload process, we'd swap the local id of the uploaded image
with the server id. This should be fine, except we use the id for a
`key` in an array, so that causes the `<img` tag to unmount, resulting
in a flash as the new image loads in.
Normally if you change the `src` of an image, the browser will wait for
the new one to load before swapping it out, but since we were using a
`key`, the `<img` tag was being deleted and added back to the DOM.
Before realizing `key` was the issue, was going to go the route of
preloading the image with:
```ts
const preload = (src: string) => {
const img = new Image()
img.src = src
return img.decode()
}
```
which worked, but fixing the key issue seems better although not sure.
PS: also added error handling for when the upload API fails.

fix(ui): image upload flashing

---

.circleci/config.yml

We don't really need to do this, just thought it would be interesting.
https://circleci.com/blog/how-to-output-junit-tests-through-circleci-2-0-for-expanded-insights/
https://circleci.com/docs/collect-test-data#pytest

ref(ci): store test results for vitest & pytest

---

frontend/src/pages/index/UserHome.tsx

This is inline with what google does:
- Desktop: autofocus
- Mobile: don't autofocus (otherwise the keyboard pops up and obscures most of the screen!)

fix(ui): stop search autofocusing on mobile

---

frontend/src/hooks.ts
frontend/src/pages/recipe-detail/RecipeTitle.tsx
frontend/src/pages/recipe-detail/RecipeTitleDropdown.tsx
frontend/src/pages/recipe-detail/ScheduleModal.tsx

Previously we only linked to the schedule page with the recipe list filtered to the given recipe, but this didn't work on mobile because the recipe list doesn't show up on mobile.

add(ui): mobile scheduling

---

.circleci/config.yml
frontend/react.Dockerfile
frontend/src/settings.ts
frontend/vite.config.ts

vite will only pass in env vars to the build that have a given prefix.
This defaults to `VITE_` so we update the config to use `FRONTEND_`.
see: https://vitejs.dev/config/shared-options.html#envprefix

fix(ui): env vars not being passed in

---

frontend/src/components/Buttons.tsx
frontend/src/components/Nav.tsx
frontend/src/components/scss/nav.scss

Rename schedule to calendar so it's clear it's not for scheduling the current recipe
Also make the nav items smaller so they don't seem like primary actions
Minor change to buttons to be a little more round

ref(ui): smaller nav items, rename schedule tab

---

frontend/src/components/Buttons.tsx
frontend/src/components/Forms.tsx
frontend/src/components/Nav.tsx
frontend/src/pages/recipe-detail/RecipeTitleDropdown.tsx

Adding the fs-14px also updated all the buttons which made the calendar nav look weird.
This reverts that change so we only adjust the size on the detail page.

fix(ui): calendar nav style regression

---

backend/core/cumin/quantity.py
backend/core/cumin/test_quantity.py
frontend/src/pages/recipe-detail/IngredientView.tsx
frontend/src/pages/recipe-detail/ScheduleModal.tsx

Now we bold the ingredient quantities a bit to make it easier to parse -- that's the idea anyway.
Also another schedule -> calendar copy change & a parser fix
Before:
After:

ref(ui): bold ingredient quantities

---

backend/core/cumin/quantity.py
backend/core/cumin/test_quantity.py

Fix a couple more cases with the recipe scraper's ingredient parsing.

fix(api): scraper parsing of '7 to 8 cups'

---

backend/core/export/serializers.py
backend/core/export/test_export.py

Trying to test out algolia and `tags` are missing in the export but we use them in the current client side search:
https://github.com/recipeyak/recipeyak/blob/0eb33a59aedfe6737d46db608b47ad87cf5d458c/frontend/src/search.ts#L34-L34
We also need the `id` so we can filter by the id.

add(api): recipe tags in export

---

frontend/src/pages/recipe-detail/RecipeDetail.page.tsx

We already sort ingredients now we sort steps as well in the UI since the API doesn't return the steps sorted.
I'm not sure why, but the UI was flipping from unsorted to sorted, but I think this should fix that.
https://user-images.githubusercontent.com/7340772/192419568-1e055d35-33cf-4985-83fd-4e911e69be64.mov

fix(ui): sort steps in components

---

backend/core/recipes/serializers.py
backend/core/views/recipe_list_view.py
frontend/src/search.test.ts
frontend/src/store/reducers/recipes.ts

We don't use this anymore -- probably haven't in a very very long time since it was typed as `unknown[]` in the UI.

ref(api): cut dead api field 'edits'

---

frontend/src/components/scss/helpers.scss
frontend/src/components/scss/main.scss
frontend/src/pages/recipe-list/RecipeList.page.tsx

added a result count w/ archived filtering (since we don't usually want to see it) along with a style change to the browser recipes list view

add(ui): results info to search

---

frontend/src/pages/recipe-list/RecipeList.page.tsx

I set the font to 14px for the input but that causes zoom on mobile -- whoops!
https://css-tricks.com/16px-or-larger-text-prevents-ios-form-zoom/
https://stackoverflow.com/questions/6030319/how-to-trigger-iphone-zoom-out-after-auto-zoom-in-to-a-form/33654789#33654789

fix(ui): search input zoom on mobile

---

backend/core/recipes/scraper.py

We shouldn't say we accept compression if we don't handle it.

fix(api): scraper accepting compressed data

---

backend/core/recipes/scraper.py
backend/core/views/recipe_list_view.py

I think we should probably have some more clearly defined "one way" to create a recipe row.

fix(api): ingredient and step ordering for scraper

---

frontend/src/components/scss/buttons.scss
frontend/src/pages/recipe-detail/ListItem.tsx

We were using the primary color as the basis for the background colors of all disabled buttons -- whoops
Also fix an edit mode tooltip that was showing up in non-edit mode.

fix(ui): background color for disabled buttons

---

frontend/src/components/scss/helpers.scss
frontend/src/components/scss/main.scss
frontend/src/pages/recipe-detail/IngredientView.tsx
frontend/src/pages/recipe-detail/ListItem.tsx
frontend/src/pages/recipe-detail/MetaData.tsx
frontend/src/pages/recipe-detail/Notes.tsx
frontend/src/pages/recipe-detail/RecipeTitle.tsx

`user-select: none;` and `cursor: default;` all the things except Recipe title, author, ingredients, steps, and notes.
rel: https://steve.dignam.xyz/2022/11/19/cursor-pointer-user-select-none/

ref(ui): user-select: none;cursor: default

---

frontend/src/pages/schedule/ShoppingList.tsx

The `user-select: none` work had a casualty: the shopping list copy.
This PR updates the generated list to be user selectable, which is
necessary for how the copy button works.

fix(ui): shopping list select

---

backend/recipeyak/cumin/quantity.py
backend/recipeyak/cumin/test_quantity.py

ensure `1¾ cups` expands to `1 3/4 cups`, not `13/4 cups`

fix(api): expanding fractions

---

frontend/src/components/scss/helpers.scss

Idk if it's windows or Firefox, probably Firefox, but we need to make it user-select: text instead of initial
Stole it from tailwinds which we should probably be using already ugh

fix(ui): selecting css on windows

---

backend/recipeyak/api/calendar_detail_view.py

The calendar item update API was missing the `on` field in the response and we didn't have io-ts or type checking to helps us

fix(api): missing field in api

---

frontend/src/pages/recipe-detail/RecipeDetail.page.tsx

Add a better `og:title` via some hacky JS so that using the iOS share sheet works well in addition to the unfurling logic for links.
I think ideally we'd render all the meta tags on the server but this is good enough for now
the [react-helmet-async](https://github.com/staylor/react-helmet-async) library we using will create dupe meta tags with the same property name which isn't what we want so we do it ourselves

fix(ui): meta tag ios share

---

frontend/src/pages/schedule/CalendarDayItem.tsx

This causes a lot of weird behavior and unexpected deletions. We want to make it harder to accidentally remove a scheduled recipe, so now we do nothing when a recipe is dropped on an unknown target.

don't remove scheduled recipes on drop of unknown target

---

backend/recipeyak/api/notes_view.py
backend/recipeyak/api/notes_view_test.py
frontend/src/pages/recipe-detail/Notes.tsx

We now hide the `edit` button for notes that a user doesn't own and prevent updating them at the API level.

fix(ui,api): prevent editing other peoples notes

---

nginx/general_headers.conf

For some reason Safari is totally cool with `data:` images without explicitly having it in the CSP header but Chrome logs an error and doesn't load them.
This means that without the header update, the place holder images don't load in chrome.

fix(ui): CSP image policy `data:`

---

.vscode/settings.json

prevents git ignored files and folders from showing up in the file explorer

fix(vscode): hide .venv and node_modules

---

nginx/nginx.conf

default gravatar caches for 5mins, this should hopefully allow for staleness of up to 7 days

update(nginx): cache gravatar for longer

---

frontend/src/pages/recipe-detail/RecipeDetail.page.tsx

not entirely sure if we want async or sync
sometimes safari on iOS gets stuck loading images, granted, these images are large, like 10 MB:
rel: https://stackoverflow.com/a/66967317/3720597
rel: https://css-tricks.com/newsletter/249-decoding-async-tree-rings-and-flexbox-gap/
This suggests using `"sync"`:
https://stackoverflow.com/a/58323810/3720597

fix(ui): header image decoding ios safari

---

backend/recipeyak/api/calendar_detail_view.py
backend/recipeyak/api/calendar_generic_view_test.py
backend/recipeyak/api/calendar_list_view.py
backend/recipeyak/api/team_calendar_test.py
backend/recipeyak/models/scheduled_recipe.py
frontend/src/api.ts
frontend/src/pages/recipe-detail/ScheduleModal.tsx
frontend/src/pages/schedule/CalendarDay.tsx
frontend/src/pages/schedule/CalendarDayItem.tsx
frontend/src/queries/scheduledRecipeCreate.ts
frontend/src/store/reducers/calendar.ts

Removed most of the UI related functionality in an earlier PR but this removes all the UI references.
We still return the params in the API to support older UI clients, but later we can remove those too.
We didn't really use the count feature and it was rather complicated.

ref(api,ui): remove count from scheduled recipes

---

frontend/src/components/Markdown.tsx

This helps with dividing steps visually

add margin between markdown paragraphs.

---

backend/recipeyak/api/recipe_bot_detail_view.py
frontend/src/pages/recipe-detail/ImageGallery.tsx
frontend/src/pages/recipe-detail/Notes.tsx
frontend/src/pages/recipe-detail/RecipeDetail.page.tsx
frontend/src/utils/url.ts

On slow connections, serving full size 2MB-4MB images is too slow. We need to compress our images to improve load times.
These Imgix settings don't appear to cause any negative display issues, and allow us to serve one image for the thumbnails, recipe header, and gallery. This improves our cache hit ratio and makes the Gallery more responsive.
I also fixed an encoding issue with our iMessage response.

compress images with imgix

---

frontend/src/pages/recipe-list/RecipeItem.tsx

CSS' `filter: blur(6px);` and `backdrop-filter: blur(6px);` are slow and really really slow in Safari.
This means searching on the recipe list page is really slow with the placeholder image blurring setup.
Some ideas for fixes:
- improve filter perf in the browser
- `IntersectionObserver` to only use blur for images that are in view
- windowing / virtualization in general for the list view
- delete the blur
going with delete the blur for now as it's the easiest
rel: https://discourse.webflow.com/t/my-site-is-extremely-slow-in-safari-practically-unusable/167272/9
rel: https://graffino.com/til/CjT2jrcLHP-how-to-fix-filter-blur-performance-issue-in-safari
rel: https://stackoverflow.com/questions/31713468/css-blur-filter-performance

fix(ui): recipe list perf issue with css blur

---

frontend/src/components/Image.tsx
frontend/src/pages/recipe-list/RecipeItem.tsx

We were rounding the images inside the card when it has square corners

fix(ui): rounding images on browse page

---

frontend/src/pages/recipe-detail/IngredientView.tsx
frontend/src/pages/recipe-detail/RecipeTitleDropdown.tsx

Before rendering in the UI / the copy to clipboard, we trim excess whitespace

fix(ui): trim ingredients

---

frontend/src/components/App.tsx
frontend/src/pages/recipe-detail/AddIngredient.tsx
frontend/src/pages/recipe-detail/Ingredient.tsx
frontend/src/pages/recipe-detail/Notes.tsx
frontend/src/pages/recipe-detail/Section.tsx
frontend/src/queries/ingredientCreate.ts
frontend/src/queries/recipeList.ts

We were saving too much data to localStorage and react-query was silently erroring.
Now we report serialize, deserialize, and storage related errors to Sentry.
Also fix some issues with `optional` settings in ingredient forms & adjust some copy.
rel: https://github.com/TanStack/query/discussions/4730

fix(ui): react-query persistence

---

frontend/src/api.ts
frontend/src/pages/recipe-detail/ScheduleModal.tsx
frontend/src/pages/recipe-list/RecipeItem.tsx
frontend/src/pages/schedule/CalendarDay.tsx
frontend/src/queries/scheduledRecipeCreate.ts

We aren't caching all the recipes at the moment and the optimistic save was reaching into the cache and not finding anything.
Now we pass in the necessary values as props.

fix(ui): optimistic updates for calendar scheduling

---

backend/recipeyak/api/calendar_list_view.py
backend/recipeyak/api/recipe_list_view.py

from tailing postgres logs I think I fixed the n + 1 queries, Django ORM doesn't make it easy

fix(api): n + 1 queries with calendar list & recipe list

---

backend/recipeyak/jobs/backfill_image_placeholders.py
frontend/src/components/Image.tsx

we were skipping images that weren't attached to notes, aka ones that we scrape for the initial primary image
also I think rendering a background-image with an empty string url results in some glitchy looking UI but not 100% sure. So now we don't include the css property when we don't have a backgroundImage url.

fix(api): primary image backfill

---

frontend/src/pages/recipe-list/RecipeItem.tsx

looks a little nicer with less space between lines in the recipe titles
Before:
After:

ref(ui): tighten spacing of list view cards

---

frontend/src/components/scss/main.scss
frontend/src/pages/recipe-list/RecipeList.page.tsx

- now we use auto-fill for our grid so that individual grid items don't expand the entire width:
https://defensivecss.dev/tip/auto-fit-fill/
- remove the search query param when it's empty
Also I was futzing around with `translate3D` and `loading=lazy` for the images but I didn't see any noticeable performance difference in the browse list

ref(ui): browse from auto-fit to auto-fill, ignore empty search param

---

backend/recipeyak/cumin/__snapshots__/cat_test.ambr
backend/recipeyak/cumin/cat.py
backend/recipeyak/cumin/cat_test.py

fix categorization for fennel seed
we could do something more special for items with "seed" in the name, but for now we're continuing with the hard coded approach.

fix(api): category for fennel seed

---

frontend/src/components/Image.tsx
frontend/src/pages/recipe-list/RecipeItem.tsx
frontend/src/pages/recipe-list/RecipeList.page.tsx
frontend/src/useIntersectionObserver.ts

Trying out https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
via https://usehooks-ts.com/react-hook/use-intersection-observer
also helpful: https://blog.webdevsimplified.com/2022-01/intersection-observer/
A big problem with the list view was the paint/layout taking a while with all the large-ish images.
This is an attempt to avoid loading all them at once.

ui: lazy load images in browse list view

---

frontend/src/components/Image.tsx

I'm not sure why, but backdrop-filter seems to get prefix on dev but not in prod.
from https://github.com/styled-components/styled-components/issues/1045#issuecomment-319359844 it seems like it should be prefixed but doesn't seem to be happening.
related about a bug in an older version but we're on a version newer than that: https://github.com/thysultan/stylis/issues/75#issuecomment-346366676

ui: fix background blur for image

---

frontend/src/pages/recipe-detail/ScheduleModal.tsx
frontend/src/pages/schedule/CalendarDayItemModal.tsx

probably need to bite the bullet at some point and use a custom input for dates, but for now this is fine
trying to get iOS and Mac OS to match up is annoying

ui: fix date input width

---

frontend/src/pages/recipe-create/RecipeCreate.page.tsx

render the API response data error instead of the Axios error message for a 400.

ui: fix add recipe import error message

---

backend/recipeyak/api/serializers/recipe.py
backend/recipeyak/models/recipe.py
frontend/src/api.ts
frontend/src/clock.svg
frontend/src/components/Buttons.tsx
frontend/src/components/Routing.tsx
frontend/src/components/icons.tsx
frontend/src/date.ts
frontend/src/pages/recipe-detail/RecipeDetail.page.tsx
frontend/src/pages/recipe-detail/RecipeTitleDropdown.tsx
frontend/src/pages/recipe-detail/ScheduleModal.tsx
frontend/src/utils/querystring.ts

Now when you use the schedule modal on a recipe we show links to recent schedules (basically to avoid you scheduling the same recipe twice)

ui: recipe-detail show recent schedules

---

frontend/src/date.test.ts
frontend/src/date.ts
frontend/src/pages/recipe-detail/ScheduleModal.tsx

we were including hours in our date calculations which resulted in errors
also added an empty state (hide the UI) when there aren't any recently scheduled entries.

ui: recipe-detail recent schedules date issues & empty state

---

frontend/.eslintrc.js
frontend/package.json
frontend/src/pages/index/UserHome.tsx
frontend/src/queries/inviteList.ts
frontend/src/queries/recentlyCreatedRecipesList.ts
frontend/src/queries/recentlyViewedRecipesList.ts
frontend/src/queries/recipeFetch.ts
frontend/src/queries/recipeList.ts
frontend/src/queries/schedulePreviewList.ts
frontend/src/queries/sessionList.ts
frontend/src/queries/shoppingListFetch.ts
frontend/src/queries/teamFetch.ts
frontend/src/queries/teamList.ts
frontend/src/queries/teamMembersList.ts
frontend/src/queries/timelineList.ts
frontend/src/queries/userFetch.ts
frontend/yarn.lock

https://tanstack.com/query/v4/docs/react/eslint/eslint-plugin-query
I don't really feel like the object syntax is super important but it seems like the exhaustive-deps doesn't work without it.
without object-syntax, the bug in:
```ts
useQuery([teamId, "schedule"], () =>
getCalendarRecipeListRequestBuilder({
teamID,
start,
end,
})
.send()
.then(unwrapEither),
)
```
isn't detected

ui: react-query eslint

---

frontend/src/components/Image.tsx
frontend/src/useIntersectionObserver.ts

when naving back from the detail page to the list view the images will hide and then pop in when we've already loaded them.
this pr updates the useIntersectionObserver to keep a cache of urls we've already seen / intend to keep loaded so we don't have this flash

ui: hacky fix for intersection observer lazy loading images

---

frontend/src/components/scss/helpers.scss

this aligns with images with the 6px radius seen in related components

ui: fix notes image border radius

---

frontend/src/query-parser.test.ts
frontend/src/query-parser.ts

support Ingredient:foo in addition to ingredient:foo

ui: fix client side filter parsing to allow capitalized versions

---

.circleci/config.yml
backend/recipeyak/cumin/quantity.py
backend/recipeyak/cumin/quantity_test.py

seems like they're called coordinate commas so we're using a slightly less naive heuristic compared to before

api: fix parsing ingredients with commas

---

backend/recipeyak/api/serializers/recipe.py
backend/recipeyak/models/recipe.py
frontend/src/api.ts
frontend/src/pages/recipe-detail/Notes.tsx
frontend/src/pages/schedule/CalendarDayItemModal.tsx

Before:
After:
For manually entered recipes it will say `created` instead of `imported`

ui,api: show 'imported' in timeline for scraped

---

frontend/src/queries/scheduledRecipeList.ts

```
[16/Sep/2023 17:44:06] "GET /api/v1/auth/ably?rnd=06675516961737249 HTTP/1.1" 301 0
[16/Sep/2023 17:44:06] "GET /api/v1/auth/ably/?rnd=06675516961737249 HTTP/1.1" 200 208
```
after:
```
[17/Sep/2023 03:57:57] "GET /api/v1/auth/ably/?rnd=2287839871387971 HTTP/1.1" 200 208
```

ui: fix 301 with ably auth api

---

infra/systemd-services/recipeyak-backfill_image_placeholders.service
infra/systemd-services/recipeyak-backup-postgres.service
infra/systemd-services/recipeyak-remove_old_checklists.service

The backfill image job got stuck. This should prevent that in the future.
The 10 minutes is pretty arbitrary. Most jobs finish in under a second

kill systemd jobs after 10 minutes

---

frontend/src/components/Markdown.tsx
frontend/src/pages/profile/Profile.page.tsx
frontend/src/pages/recipe-detail/Notes.tsx
frontend/src/pages/recipe-detail/RecipeDetail.page.tsx
frontend/src/pages/recipe-detail/Section.tsx
frontend/src/pages/recipe-detail/Step.tsx

- make section titles selectable
- normalize notes (aka tablespoon and Teaspoon)
- also refactor <Markdown a bit to include selectable class
- fix sub-day ordering in profile activity, the items during the day weren't ordered properly
- fix selecting on the recipe page by avoiding some css grid

ui: selectable section titles, normalized notes

---

frontend/src/components/Markdown.tsx
frontend/src/pages/recipe-detail/IngredientView.tsx
frontend/src/themeConstants.ts

Alternative considered, using underline instead of changing the text color:
```js
export const THEME_CSS_BAKING_SODA =
"underline decoration-red-500 underline-offset-2 italic"
export const THEME_CSS_BAKING_POWDER =
"underline decoration-pink-400 underline-offset-2"
```

ui: highlight baking soda and powder

---

.github/workflows/infrastructure.yml
frontend/react.Dockerfile

Building outside of the container lets us use GitHub Actions caching more easily

improve react docker build times

---

backend/recipeyak/django/settings.py

etags don't work with cache-control: no-store

api: remove unnecessary middleware

---

backend/pyproject.toml
backend/recipeyak/api/upload_start_view.py
backend/recipeyak/cumin/cat.py
backend/recipeyak/cumin/cat_test.py
backend/recipeyak/models/upload.py
backend/recipeyak/scraper/scrape_recipe.py
backend/recipeyak/storage.py
frontend/src/pages/recipe-list/RecipeListSearch.tsx
frontend/src/pages/team-detail/Members.tsx

pytest is still super slow -- largely because it runs everything in serial
Was benchmarking the collect with --collect-only and also just running the tests
```sh
export TESTING=1
export DATABASE_URL=postgres://postgres:postgres@127.0.0.1:5432/postgres
export DEBUG=1
export DJANGO_SETTINGS_MODULE="recipeyak.django.settings"
ARGS="${@}"
time py-spy record -r 200 --format speedscope -o test -- ./.venv/bin/pytest $ARGS
```
Then viewing the json in: https://www.speedscope.app
[py_spy_profile.speedscope.json](https://github.com/recipeyak/recipeyak/files/13910257/py_spy_profile.speedscope.json)

api: improve pytest startup

---

frontend/src/components/Markdown.tsx
frontend/src/components/NavRecipeSearch.tsx
frontend/src/pages/recipe-detail/Notes.tsx
frontend/src/pages/schedule/ScheduleRecipeModal.tsx

for some reason the eslint tailwind plugin wasn't warning about: last-child:mb-0 being an invalid class so we were getting extra padding in comments. Also adjusted the gap a bit and dom structure to avoid some spacing.

ui: cleanup spacing in notes aka comments

---

frontend/src/components/AlgoliaProvider.tsx
frontend/src/components/algoliaContext.ts
frontend/src/queries/searchRecipeFacets.ts
frontend/src/queries/searchRecipes.ts
frontend/src/queries/useAlgoliaClient.ts

Previously we'd do nothing if algolia wasn't loaded when we made a query. Now we wait for the client before making a query.

wait for algolia to load before making queries

---

frontend/src/pages/recipe-list/RecipeItem.tsx

Previously there was a small gap between the border and the image

correctly round browse page image corners

---

frontend/s/dev
frontend/src/components/Buttons.tsx
frontend/src/pages/recipe-detail/ScheduleModal.tsx
frontend/src/pages/schedule/CalendarDayItem.tsx
frontend/src/pages/schedule/ScheduleRecipeModal.tsx

messing around with inputs as well as buttons, but not sure the ideal behavior for text inputs yet -- do we want to show the outline only on desktop or all the time?
buttons no longer show a focus right on pressing which is better and more native like

ui: adjust focus rings so they don't show up mobile

---

frontend/src/components/NavLink.tsx

clicking on the nav link shouldn't trigger an outline

ui: fix focus ring on nav links

---

frontend/src/pages/schedule/ScheduledRecipeEditModal.tsx

This change prevents zooming on iOS when a user taps the date picker

fix font size for rescheduling recipe

---

frontend/src/components/CloseButton.tsx

took me a while to find the existing issue, but clicking on the modal's close button would trigger the elements underneath it.
tried sprinkling some `preventDefault`s on the elements above the button but that didn't work. instead swapping out the usePress powered `<Button` for an ol' fashioned onClick `<button`
see: https://github.com/adobe/react-spectrum/issues/1513

ui: workaround for react-aria bug

---

backend/recipeyak/jobs/backfill_image_placeholders.py

if there are no rows found we can exit

api: return early from backfill image placeholder job

---

backend/recipeyak/scraper/extract.py

fixes https://magnus-montis.sentry.io/issues/4985854938/events/21b3c25e185d4ca8a2366dead3cb75f3/
TypeError
unsupported operand type(s) for *: 'NoneType' and 'int'

fix time parsing error

---

backend/poetry.lock
backend/pyproject.toml
backend/s/test

still slow, but ~3.5s instead of ~6s
I think the spinning up test databases for each processes is not great and I don't think it runs the tests in parallel in each process

api: use pytest-xdist to parallelize tests

---

frontend/.eslintrc.cjs
frontend/package.json
frontend/yarn.lock

isn't necessary, see:
https://www.joshuakgoldberg.com/blog/you-probably-dont-need-eslint-config-prettier-or-eslint-plugin-prettier/

ui: remove eslint-config-prettier

---

frontend/src/pages/recipe-detail/Ingredient.tsx
frontend/src/pages/recipe-detail/Section.tsx
frontend/src/pages/recipe-detail/Step.tsx

ui: remove incorrect element titles

---

backend/poetry.lock
backend/pyproject.toml

https://adamj.eu/tech/2021/01/20/efficient-reloading-in-djangos-runserver-with-watchman/
https://twitter.com/AdamChainz/status/1770755957133287643
reduces ambient CPU usage from 3.5% of a core to 0% on my laptop
Before:
After:

api: use watchman instead of polling for file reload with django

---

frontend/src/components/Nav.tsx
frontend/src/components/NavRecipeSearch.tsx
frontend/src/components/Page.tsx
frontend/src/pages/recipe-list/RecipeListSearch.tsx

for some reason position: fixed doesn't work the same as it does on MacOS
so instead we move the search palette around a bit in the DOM which should help

ui: fix search palette being cut off on iOS

---

backend/recipeyak/parsing.py
backend/recipeyak/parsing_test.py

before the quantity of:
```
1 cup plus 2 Tablespoons/148 grams all-purpose flour
```
would be:
```
1 cup plus 2
```
instead of:
```
1 cup plus 2 Tablespoons/148 grams
```

api: fix parsing ingredients with slashes

---

frontend/src/components/NavRecipeSearch.tsx

Now the search text focuses and the keyboard appears on iOS.
I think this broke with 680d3fcc247972c4907cfcd9138d74f4d151d3d1

fix clicking on search icon in bottom toolbar
